import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 17400,
      endTimeSeconds: 86400,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const SP_L3: LineDefinition = {
  line: { id: "SP_L3", name: "Linha 3 - Vermelha", color: "#EE3124" },
  platforms: [
    { id: "plt_barra_funda_l3", stationId: "st_barra_funda", lineId: "SP_L3" },
    {
      id: "plt_marechal_deodoro_l3",
      stationId: "st_marechal_deodoro",
      lineId: "SP_L3",
    },
    {
      id: "plt_santa_cecilia_l3",
      stationId: "st_santa_cecilia",
      lineId: "SP_L3",
    },
    { id: "plt_republica_l3", stationId: "st_republica", lineId: "SP_L3" },
    { id: "plt_anhangabau_l3", stationId: "st_anhangabau", lineId: "SP_L3" },
    { id: "plt_se_l3", stationId: "st_se", lineId: "SP_L3" },
    { id: "plt_pedro_ii_l3", stationId: "st_pedro_ii", lineId: "SP_L3" },
    { id: "plt_bras_l3", stationId: "st_bras", lineId: "SP_L3" },
    {
      id: "plt_bresser_mooca_l3",
      stationId: "st_bresser_mooca",
      lineId: "SP_L3",
    },
    { id: "plt_belem_l3", stationId: "st_belem", lineId: "SP_L3" },
    { id: "plt_tatuape_l3", stationId: "st_tatuape", lineId: "SP_L3" },
    { id: "plt_carrao_l3", stationId: "st_carrao", lineId: "SP_L3" },
    { id: "plt_penha_l3", stationId: "st_penha", lineId: "SP_L3" },
    {
      id: "plt_vila_matilde_l3",
      stationId: "st_vila_matilde",
      lineId: "SP_L3",
    },
    {
      id: "plt_guilhermina_esperanca_l3",
      stationId: "st_guilhermina_esperanca",
      lineId: "SP_L3",
    },
    { id: "plt_patriarca_l3", stationId: "st_patriarca", lineId: "SP_L3" },
    { id: "plt_artur_alvim_l3", stationId: "st_artur_alvim", lineId: "SP_L3" },
    {
      id: "plt_corinthians_itaquera_l3",
      stationId: "st_corinthians_itaquera",
      lineId: "SP_L3",
    },
  ],
  segments: [
    {
      id: "seg_barrafunda_marechal_l3",
      fromPlatformId: "plt_barra_funda_l3",
      toPlatformId: "plt_marechal_deodoro_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_marechal_santacecilia_l3",
      fromPlatformId: "plt_marechal_deodoro_l3",
      toPlatformId: "plt_santa_cecilia_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 950,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_santacecilia_republica_l3",
      fromPlatformId: "plt_santa_cecilia_l3",
      toPlatformId: "plt_republica_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 900,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_republica_anhangabau_l3",
      fromPlatformId: "plt_republica_l3",
      toPlatformId: "plt_anhangabau_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 700,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_anhangabau_se_l3",
      fromPlatformId: "plt_anhangabau_l3",
      toPlatformId: "plt_se_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 600,
      averageDurationSeconds: 65,
      timeProfiles: p(65),
    },
    {
      id: "seg_se_pedroii_l3",
      fromPlatformId: "plt_se_l3",
      toPlatformId: "plt_pedro_ii_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 700,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_pedroii_bras_l3",
      fromPlatformId: "plt_pedro_ii_l3",
      toPlatformId: "plt_bras_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 850,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_bras_bresser_l3",
      fromPlatformId: "plt_bras_l3",
      toPlatformId: "plt_bresser_mooca_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 900,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_bresser_belem_l3",
      fromPlatformId: "plt_bresser_mooca_l3",
      toPlatformId: "plt_belem_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 950,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_belem_tatuape_l3",
      fromPlatformId: "plt_belem_l3",
      toPlatformId: "plt_tatuape_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_tatuape_carrao_l3",
      fromPlatformId: "plt_tatuape_l3",
      toPlatformId: "plt_carrao_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_carrao_penha_l3",
      fromPlatformId: "plt_carrao_l3",
      toPlatformId: "plt_penha_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 1300,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_penha_vilamatilde_l3",
      fromPlatformId: "plt_penha_l3",
      toPlatformId: "plt_vila_matilde_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_vilamatilde_guilhermina_l3",
      fromPlatformId: "plt_vila_matilde_l3",
      toPlatformId: "plt_guilhermina_esperanca_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_guilhermina_patriarca_l3",
      fromPlatformId: "plt_guilhermina_esperanca_l3",
      toPlatformId: "plt_patriarca_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 1000,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_patriarca_arturalvim_l3",
      fromPlatformId: "plt_patriarca_l3",
      toPlatformId: "plt_artur_alvim_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 1050,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_arturalvim_itaquera_l3",
      fromPlatformId: "plt_artur_alvim_l3",
      toPlatformId: "plt_corinthians_itaquera_l3",
      lineId: "SP_L3",
      direction: "INBOUND",
      sequence: 17,
      distanceMeters: 1400,
      averageDurationSeconds: 100,
      timeProfiles: p(100),
    },
  ],
};
