import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 17400,
      endTimeSeconds: 86400,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const SP_L2: LineDefinition = {
  line: { id: "SP_L2", name: "Linha 2 - Verde", color: "#007A3D" },
  platforms: [
    {
      id: "plt_vila_madalena_l2",
      stationId: "st_vila_madalena",
      lineId: "SP_L2",
    },
    { id: "plt_sumare_l2", stationId: "st_sumare", lineId: "SP_L2" },
    { id: "plt_clinicas_l2", stationId: "st_clinicas", lineId: "SP_L2" },
    { id: "plt_consolacao_l2", stationId: "st_consolacao", lineId: "SP_L2" },
    {
      id: "plt_trianon_masp_l2",
      stationId: "st_trianon_masp",
      lineId: "SP_L2",
    },
    { id: "plt_brigadeiro_l2", stationId: "st_brigadeiro", lineId: "SP_L2" },
    { id: "plt_paraiso_l2", stationId: "st_paraiso", lineId: "SP_L2" },
    { id: "plt_ana_rosa_l2", stationId: "st_ana_rosa", lineId: "SP_L2" },
    {
      id: "plt_chacara_klabin_l2",
      stationId: "st_chacara_klabin",
      lineId: "SP_L2",
    },
    {
      id: "plt_santos_imigrantes_l2",
      stationId: "st_santos_imigrantes",
      lineId: "SP_L2",
    },
    {
      id: "plt_alto_do_ipiranga_l2",
      stationId: "st_alto_do_ipiranga",
      lineId: "SP_L2",
    },
    { id: "plt_sacoma_l2", stationId: "st_sacoma", lineId: "SP_L2" },
    { id: "plt_tamanduatei_l2", stationId: "st_tamanduatei", lineId: "SP_L2" },
    {
      id: "plt_vila_prudente_l2",
      stationId: "st_vila_prudente",
      lineId: "SP_L2",
    },
  ],
  segments: [
    {
      id: "seg_vilamadalena_sumare_l2",
      fromPlatformId: "plt_vila_madalena_l2",
      toPlatformId: "plt_sumare_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_sumare_clinicas_l2",
      fromPlatformId: "plt_sumare_l2",
      toPlatformId: "plt_clinicas_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 900,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_clinicas_consolacao_l2",
      fromPlatformId: "plt_clinicas_l2",
      toPlatformId: "plt_consolacao_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1000,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_consolacao_trianon_l2",
      fromPlatformId: "plt_consolacao_l2",
      toPlatformId: "plt_trianon_masp_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 950,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_trianon_brigadeiro_l2",
      fromPlatformId: "plt_trianon_masp_l2",
      toPlatformId: "plt_brigadeiro_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 950,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_brigadeiro_paraiso_l2",
      fromPlatformId: "plt_brigadeiro_l2",
      toPlatformId: "plt_paraiso_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 1000,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_paraiso_anarosa_l2",
      fromPlatformId: "plt_paraiso_l2",
      toPlatformId: "plt_ana_rosa_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 650,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_anarosa_chacaraklabin_l2",
      fromPlatformId: "plt_ana_rosa_l2",
      toPlatformId: "plt_chacara_klabin_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 1100,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_chacaraklabin_imigrantes_l2",
      fromPlatformId: "plt_chacara_klabin_l2",
      toPlatformId: "plt_santos_imigrantes_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 1200,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_imigrantes_altoipiranga_l2",
      fromPlatformId: "plt_santos_imigrantes_l2",
      toPlatformId: "plt_alto_do_ipiranga_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 1000,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_altoipiranga_sacoma_l2",
      fromPlatformId: "plt_alto_do_ipiranga_l2",
      toPlatformId: "plt_sacoma_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 1100,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_sacoma_tamanduatei_l2",
      fromPlatformId: "plt_sacoma_l2",
      toPlatformId: "plt_tamanduatei_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 1500,
      averageDurationSeconds: 110,
      timeProfiles: p(110),
    },
    {
      id: "seg_tamanduatei_vilaprudente_l2",
      fromPlatformId: "plt_tamanduatei_l2",
      toPlatformId: "plt_vila_prudente_l2",
      lineId: "SP_L2",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 1300,
      averageDurationSeconds: 100,
      timeProfiles: p(100),
    },
  ],
};
