import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 17400,
      endTimeSeconds: 86400,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const SP_L4: LineDefinition = {
  line: { id: "SP_L4", name: "Linha 4 - Amarela", color: "#FFD100" },
  platforms: [
    { id: "plt_luz_l4", stationId: "st_luz", lineId: "SP_L4" },
    { id: "plt_republica_l4", stationId: "st_republica", lineId: "SP_L4" },
    {
      id: "plt_higienopolis_mackenzie_l4",
      stationId: "st_higienopolis_mackenzie",
      lineId: "SP_L4",
    },
    { id: "plt_paulista_l4", stationId: "st_paulista", lineId: "SP_L4" },
    {
      id: "plt_oscar_freire_l4",
      stationId: "st_oscar_freire",
      lineId: "SP_L4",
    },
    {
      id: "plt_fradique_coutinho_l4",
      stationId: "st_fradique_coutinho",
      lineId: "SP_L4",
    },
    { id: "plt_faria_lima_l4", stationId: "st_faria_lima", lineId: "SP_L4" },
    { id: "plt_pinheiros_l4", stationId: "st_pinheiros", lineId: "SP_L4" },
    { id: "plt_butanta_l4", stationId: "st_butanta", lineId: "SP_L4" },
    {
      id: "plt_sao_paulo_morumbi_l4",
      stationId: "st_sao_paulo_morumbi",
      lineId: "SP_L4",
    },
    { id: "plt_vila_sonia_l4", stationId: "st_vila_sonia", lineId: "SP_L4" },
  ],
  segments: [
    {
      id: "seg_luz_republica_l4",
      fromPlatformId: "plt_luz_l4",
      toPlatformId: "plt_republica_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_republica_mackenzie_l4",
      fromPlatformId: "plt_republica_l4",
      toPlatformId: "plt_higienopolis_mackenzie_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1000,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_mackenzie_paulista_l4",
      fromPlatformId: "plt_higienopolis_mackenzie_l4",
      toPlatformId: "plt_paulista_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 900,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_paulista_oscarfreire_l4",
      fromPlatformId: "plt_paulista_l4",
      toPlatformId: "plt_oscar_freire_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_oscarfreire_fradique_l4",
      fromPlatformId: "plt_oscar_freire_l4",
      toPlatformId: "plt_fradique_coutinho_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_fradique_farialima_l4",
      fromPlatformId: "plt_fradique_coutinho_l4",
      toPlatformId: "plt_faria_lima_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 950,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_farialima_pinheiros_l4",
      fromPlatformId: "plt_faria_lima_l4",
      toPlatformId: "plt_pinheiros_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 800,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_pinheiros_butanta_l4",
      fromPlatformId: "plt_pinheiros_l4",
      toPlatformId: "plt_butanta_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 1500,
      averageDurationSeconds: 110,
      timeProfiles: p(110),
    },
    {
      id: "seg_butanta_morumbi_l4",
      fromPlatformId: "plt_butanta_l4",
      toPlatformId: "plt_sao_paulo_morumbi_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 1800,
      averageDurationSeconds: 120,
      timeProfiles: p(120),
    },
    {
      id: "seg_morumbi_vilasonia_l4",
      fromPlatformId: "plt_sao_paulo_morumbi_l4",
      toPlatformId: "plt_vila_sonia_l4",
      lineId: "SP_L4",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 1500,
      averageDurationSeconds: 110,
      timeProfiles: p(110),
    },
  ],
};
