import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 17400,
      endTimeSeconds: 86400,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const SP_L15: LineDefinition = {
  line: { id: "SP_L15", name: "Linha 15 - Prata", color: "#9E9E9E" },
  platforms: [
    {
      id: "plt_vila_prudente_l15",
      stationId: "st_vila_prudente",
      lineId: "SP_L15",
    },
    { id: "plt_oratorio_l15", stationId: "st_oratorio", lineId: "SP_L15" },
    { id: "plt_sao_lucas_l15", stationId: "st_sao_lucas", lineId: "SP_L15" },
    {
      id: "plt_camilo_haddad_l15",
      stationId: "st_camilo_haddad",
      lineId: "SP_L15",
    },
    {
      id: "plt_vila_tolstoi_l15",
      stationId: "st_vila_tolstoi",
      lineId: "SP_L15",
    },
    { id: "plt_vila_uniao_l15", stationId: "st_vila_uniao", lineId: "SP_L15" },
    {
      id: "plt_jardim_planalto_l15",
      stationId: "st_jardim_planalto",
      lineId: "SP_L15",
    },
    { id: "plt_sapopemba_l15", stationId: "st_sapopemba", lineId: "SP_L15" },
    {
      id: "plt_fazenda_da_juta_l15",
      stationId: "st_fazenda_da_juta",
      lineId: "SP_L15",
    },
    { id: "plt_sao_mateus_l15", stationId: "st_sao_mateus", lineId: "SP_L15" },
    {
      id: "plt_jardim_colonial_l15",
      stationId: "st_jardim_colonial",
      lineId: "SP_L15",
    },
  ],
  segments: [
    {
      id: "seg_vilaprudente_oratorio_l15",
      fromPlatformId: "plt_vila_prudente_l15",
      toPlatformId: "plt_oratorio_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_oratorio_saolucas_l15",
      fromPlatformId: "plt_oratorio_l15",
      toPlatformId: "plt_sao_lucas_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_saolucas_camilohaddad_l15",
      fromPlatformId: "plt_sao_lucas_l15",
      toPlatformId: "plt_camilo_haddad_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1000,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_camilohaddad_vilatolstoi_l15",
      fromPlatformId: "plt_camilo_haddad_l15",
      toPlatformId: "plt_vila_tolstoi_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 950,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_vilatolstoi_vilauniao_l15",
      fromPlatformId: "plt_vila_tolstoi_l15",
      toPlatformId: "plt_vila_uniao_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 900,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_vilauniao_jdplanalto_l15",
      fromPlatformId: "plt_vila_uniao_l15",
      toPlatformId: "plt_jardim_planalto_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 1000,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_jdplanalto_sapopemba_l15",
      fromPlatformId: "plt_jardim_planalto_l15",
      toPlatformId: "plt_sapopemba_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_sapopemba_fazendajuta_l15",
      fromPlatformId: "plt_sapopemba_l15",
      toPlatformId: "plt_fazenda_da_juta_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_fazendajuta_saomateus_l15",
      fromPlatformId: "plt_fazenda_da_juta_l15",
      toPlatformId: "plt_sao_mateus_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 1300,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_saomateus_jdcolonial_l15",
      fromPlatformId: "plt_sao_mateus_l15",
      toPlatformId: "plt_jardim_colonial_l15",
      lineId: "SP_L15",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 1400,
      averageDurationSeconds: 100,
      timeProfiles: p(100),
    },
  ],
};
