import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 17400,
      endTimeSeconds: 86400,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const SP_L1: LineDefinition = {
  line: { id: "SP_L1", name: "Linha 1 - Azul", color: "#0055A5" },
  platforms: [
    { id: "plt_tucuruvi_l1", stationId: "st_tucuruvi", lineId: "SP_L1" },
    {
      id: "plt_parada_inglesa_l1",
      stationId: "st_parada_inglesa",
      lineId: "SP_L1",
    },
    {
      id: "plt_jardim_sao_paulo_l1",
      stationId: "st_jardim_sao_paulo",
      lineId: "SP_L1",
    },
    { id: "plt_santana_l1", stationId: "st_santana", lineId: "SP_L1" },
    { id: "plt_carandiru_l1", stationId: "st_carandiru", lineId: "SP_L1" },
    {
      id: "plt_portuguesa_tiete_l1",
      stationId: "st_portuguesa_tiete",
      lineId: "SP_L1",
    },
    { id: "plt_armenia_l1", stationId: "st_armenia", lineId: "SP_L1" },
    { id: "plt_tiradentes_l1", stationId: "st_tiradentes", lineId: "SP_L1" },
    { id: "plt_luz_l1", stationId: "st_luz", lineId: "SP_L1" },
    { id: "plt_sao_bento_l1", stationId: "st_sao_bento", lineId: "SP_L1" },
    { id: "plt_se_l1", stationId: "st_se", lineId: "SP_L1" },
    { id: "plt_liberdade_l1", stationId: "st_liberdade", lineId: "SP_L1" },
    { id: "plt_sao_joaquim_l1", stationId: "st_sao_joaquim", lineId: "SP_L1" },
    { id: "plt_vergueiro_l1", stationId: "st_vergueiro", lineId: "SP_L1" },
    { id: "plt_paraiso_l1", stationId: "st_paraiso", lineId: "SP_L1" },
    { id: "plt_ana_rosa_l1", stationId: "st_ana_rosa", lineId: "SP_L1" },
    {
      id: "plt_vila_mariana_l1",
      stationId: "st_vila_mariana",
      lineId: "SP_L1",
    },
    { id: "plt_santa_cruz_l1", stationId: "st_santa_cruz", lineId: "SP_L1" },
    {
      id: "plt_praca_da_arvore_l1",
      stationId: "st_praca_da_arvore",
      lineId: "SP_L1",
    },
    { id: "plt_saude_l1", stationId: "st_saude", lineId: "SP_L1" },
    { id: "plt_sao_judas_l1", stationId: "st_sao_judas", lineId: "SP_L1" },
    { id: "plt_conceicao_l1", stationId: "st_conceicao", lineId: "SP_L1" },
    { id: "plt_jabaquara_l1", stationId: "st_jabaquara", lineId: "SP_L1" },
  ],
  segments: [
    {
      id: "seg_tucuruvi_parada_l1",
      fromPlatformId: "plt_tucuruvi_l1",
      toPlatformId: "plt_parada_inglesa_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_parada_jardim_l1",
      fromPlatformId: "plt_parada_inglesa_l1",
      toPlatformId: "plt_jardim_sao_paulo_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_jardim_santana_l1",
      fromPlatformId: "plt_jardim_sao_paulo_l1",
      toPlatformId: "plt_santana_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1500,
      averageDurationSeconds: 110,
      timeProfiles: p(110),
    },
    {
      id: "seg_santana_carandiru_l1",
      fromPlatformId: "plt_santana_l1",
      toPlatformId: "plt_carandiru_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 900,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_carandiru_tiete_l1",
      fromPlatformId: "plt_carandiru_l1",
      toPlatformId: "plt_portuguesa_tiete_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 950,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_tiete_armenia_l1",
      fromPlatformId: "plt_portuguesa_tiete_l1",
      toPlatformId: "plt_armenia_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 1300,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_armenia_tiradentes_l1",
      fromPlatformId: "plt_armenia_l1",
      toPlatformId: "plt_tiradentes_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_tiradentes_luz_l1",
      fromPlatformId: "plt_tiradentes_l1",
      toPlatformId: "plt_luz_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 800,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_luz_saobento_l1",
      fromPlatformId: "plt_luz_l1",
      toPlatformId: "plt_sao_bento_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 900,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_saobento_se_l1",
      fromPlatformId: "plt_sao_bento_l1",
      toPlatformId: "plt_se_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 600,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_se_liberdade_l1",
      fromPlatformId: "plt_se_l1",
      toPlatformId: "plt_liberdade_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 750,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_liberdade_saojoaquim_l1",
      fromPlatformId: "plt_liberdade_l1",
      toPlatformId: "plt_sao_joaquim_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 700,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_saojoaquim_vergueiro_l1",
      fromPlatformId: "plt_sao_joaquim_l1",
      toPlatformId: "plt_vergueiro_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 800,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_vergueiro_paraiso_l1",
      fromPlatformId: "plt_vergueiro_l1",
      toPlatformId: "plt_paraiso_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 700,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_paraiso_anarosa_l1",
      fromPlatformId: "plt_paraiso_l1",
      toPlatformId: "plt_ana_rosa_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 650,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_anarosa_vilamariana_l1",
      fromPlatformId: "plt_ana_rosa_l1",
      toPlatformId: "plt_vila_mariana_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 900,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_vilamariana_santacruz_l1",
      fromPlatformId: "plt_vila_mariana_l1",
      toPlatformId: "plt_santa_cruz_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 17,
      distanceMeters: 850,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_santacruz_pracaarvore_l1",
      fromPlatformId: "plt_santa_cruz_l1",
      toPlatformId: "plt_praca_da_arvore_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 18,
      distanceMeters: 750,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_pracaarvore_saude_l1",
      fromPlatformId: "plt_praca_da_arvore_l1",
      toPlatformId: "plt_saude_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 19,
      distanceMeters: 800,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_saude_saojudas_l1",
      fromPlatformId: "plt_saude_l1",
      toPlatformId: "plt_sao_judas_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 20,
      distanceMeters: 900,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_saojudas_conceicao_l1",
      fromPlatformId: "plt_sao_judas_l1",
      toPlatformId: "plt_conceicao_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 21,
      distanceMeters: 850,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_conceicao_jabaquara_l1",
      fromPlatformId: "plt_conceicao_l1",
      toPlatformId: "plt_jabaquara_l1",
      lineId: "SP_L1",
      direction: "INBOUND",
      sequence: 22,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
  ],
};
