import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 17400,
      endTimeSeconds: 86400,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const SP_L5: LineDefinition = {
  line: { id: "SP_L5", name: "Linha 5 - Lilas", color: "#9B2B8A" },
  platforms: [
    {
      id: "plt_capao_redondo_l5",
      stationId: "st_capao_redondo",
      lineId: "SP_L5",
    },
    { id: "plt_campo_limpo_l5", stationId: "st_campo_limpo", lineId: "SP_L5" },
    {
      id: "plt_vila_das_belezas_l5",
      stationId: "st_vila_das_belezas",
      lineId: "SP_L5",
    },
    {
      id: "plt_giovanni_gronchi_l5",
      stationId: "st_giovanni_gronchi",
      lineId: "SP_L5",
    },
    { id: "plt_santo_amaro_l5", stationId: "st_santo_amaro", lineId: "SP_L5" },
    { id: "plt_largo_treze_l5", stationId: "st_largo_treze", lineId: "SP_L5" },
    {
      id: "plt_adolfo_pinheiro_l5",
      stationId: "st_adolfo_pinheiro",
      lineId: "SP_L5",
    },
    {
      id: "plt_alto_da_boa_vista_l5",
      stationId: "st_alto_da_boa_vista",
      lineId: "SP_L5",
    },
    { id: "plt_borba_gato_l5", stationId: "st_borba_gato", lineId: "SP_L5" },
    { id: "plt_brooklin_l5", stationId: "st_brooklin", lineId: "SP_L5" },
    { id: "plt_campo_belo_l5", stationId: "st_campo_belo", lineId: "SP_L5" },
    { id: "plt_eucaliptos_l5", stationId: "st_eucaliptos", lineId: "SP_L5" },
    { id: "plt_moema_l5", stationId: "st_moema", lineId: "SP_L5" },
    {
      id: "plt_aacd_servidor_l5",
      stationId: "st_aacd_servidor",
      lineId: "SP_L5",
    },
    {
      id: "plt_hospital_sao_paulo_l5",
      stationId: "st_hospital_sao_paulo",
      lineId: "SP_L5",
    },
    { id: "plt_santa_cruz_l5", stationId: "st_santa_cruz", lineId: "SP_L5" },
    {
      id: "plt_chacara_klabin_l5",
      stationId: "st_chacara_klabin",
      lineId: "SP_L5",
    },
  ],
  segments: [
    {
      id: "seg_capaored_campolimpo_l5",
      fromPlatformId: "plt_capao_redondo_l5",
      toPlatformId: "plt_campo_limpo_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_campolimpo_belezas_l5",
      fromPlatformId: "plt_campo_limpo_l5",
      toPlatformId: "plt_vila_das_belezas_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1000,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_belezas_giovanni_l5",
      fromPlatformId: "plt_vila_das_belezas_l5",
      toPlatformId: "plt_giovanni_gronchi_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_giovanni_santoamaro_l5",
      fromPlatformId: "plt_giovanni_gronchi_l5",
      toPlatformId: "plt_santo_amaro_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 1500,
      averageDurationSeconds: 105,
      timeProfiles: p(105),
    },
    {
      id: "seg_santoamaro_largotreze_l5",
      fromPlatformId: "plt_santo_amaro_l5",
      toPlatformId: "plt_largo_treze_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 1300,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_largotreze_adolfo_l5",
      fromPlatformId: "plt_largo_treze_l5",
      toPlatformId: "plt_adolfo_pinheiro_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 1000,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_adolfo_altoboavista_l5",
      fromPlatformId: "plt_adolfo_pinheiro_l5",
      toPlatformId: "plt_alto_da_boa_vista_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 1400,
      averageDurationSeconds: 100,
      timeProfiles: p(100),
    },
    {
      id: "seg_altoboavista_borbagato_l5",
      fromPlatformId: "plt_alto_da_boa_vista_l5",
      toPlatformId: "plt_borba_gato_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 1000,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_borbagato_brooklin_l5",
      fromPlatformId: "plt_borba_gato_l5",
      toPlatformId: "plt_brooklin_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 900,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_brooklin_campobelo_l5",
      fromPlatformId: "plt_brooklin_l5",
      toPlatformId: "plt_campo_belo_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 800,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_campobelo_eucaliptos_l5",
      fromPlatformId: "plt_campo_belo_l5",
      toPlatformId: "plt_eucaliptos_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 1100,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_eucaliptos_moema_l5",
      fromPlatformId: "plt_eucaliptos_l5",
      toPlatformId: "plt_moema_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_moema_aacd_l5",
      fromPlatformId: "plt_moema_l5",
      toPlatformId: "plt_aacd_servidor_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 1300,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_aacd_hospitalsp_l5",
      fromPlatformId: "plt_aacd_servidor_l5",
      toPlatformId: "plt_hospital_sao_paulo_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 1000,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_hospitalsp_santacruz_l5",
      fromPlatformId: "plt_hospital_sao_paulo_l5",
      toPlatformId: "plt_santa_cruz_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 1200,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_santacruz_klabin_l5",
      fromPlatformId: "plt_santa_cruz_l5",
      toPlatformId: "plt_chacara_klabin_l5",
      lineId: "SP_L5",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 1400,
      averageDurationSeconds: 100,
      timeProfiles: p(100),
    },
  ],
};
