import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 25200,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const L1: LineDefinition = {
  line: { id: "L1", name: "Línea 1", color: "#EF4135" },
  platforms: [
    { id: "plt_san_pablo_l1", stationId: "st_san_pablo", lineId: "L1" },
    { id: "plt_neptuno_l1", stationId: "st_neptuno", lineId: "L1" },
    { id: "plt_pajaritos_l1", stationId: "st_pajaritos", lineId: "L1" },
    { id: "plt_las_rejas_l1", stationId: "st_las_rejas", lineId: "L1" },
    { id: "plt_ecuador_l1", stationId: "st_ecuador", lineId: "L1" },
    {
      id: "plt_san_alberto_hurtado_l1",
      stationId: "st_san_alberto_hurtado",
      lineId: "L1",
    },
    {
      id: "plt_universidad_de_santiago_l1",
      stationId: "st_universidad_de_santiago",
      lineId: "L1",
    },
    {
      id: "plt_estacion_central_l1",
      stationId: "st_estacion_central",
      lineId: "L1",
    },
    {
      id: "plt_union_latinoamericana_l1",
      stationId: "st_union_latinoamericana",
      lineId: "L1",
    },
    { id: "plt_republica_l1", stationId: "st_republica", lineId: "L1" },
    { id: "plt_los_heroes_l1", stationId: "st_los_heroes", lineId: "L1" },
    { id: "plt_la_moneda_l1", stationId: "st_la_moneda", lineId: "L1" },
    {
      id: "plt_universidad_de_chile_l1",
      stationId: "st_universidad_de_chile",
      lineId: "L1",
    },
    { id: "plt_santa_lucia_l1", stationId: "st_santa_lucia", lineId: "L1" },
    {
      id: "plt_universidad_catolica_l1",
      stationId: "st_universidad_catolica",
      lineId: "L1",
    },
    { id: "plt_baquedano_l1", stationId: "st_baquedano", lineId: "L1" },
    { id: "plt_salvador_l1", stationId: "st_salvador", lineId: "L1" },
    { id: "plt_manuel_montt_l1", stationId: "st_manuel_montt", lineId: "L1" },
    {
      id: "plt_pedro_de_valdivia_l1",
      stationId: "st_pedro_de_valdivia",
      lineId: "L1",
    },
    { id: "plt_los_leones_l1", stationId: "st_los_leones", lineId: "L1" },
    { id: "plt_tobalaba_l1", stationId: "st_tobalaba", lineId: "L1" },
    { id: "plt_el_golf_l1", stationId: "st_el_golf", lineId: "L1" },
    { id: "plt_alcantara_l1", stationId: "st_alcantara", lineId: "L1" },
    {
      id: "plt_escuela_militar_l1",
      stationId: "st_escuela_militar",
      lineId: "L1",
    },
    { id: "plt_manquehue_l1", stationId: "st_manquehue", lineId: "L1" },
    {
      id: "plt_hernando_de_magallanes_l1",
      stationId: "st_hernando_de_magallanes",
      lineId: "L1",
    },
    { id: "plt_los_dominicos_l1", stationId: "st_los_dominicos", lineId: "L1" },
  ],
  segments: [
    {
      id: "seg_l1_san_pablo_neptuno_inbound",
      fromPlatformId: "plt_san_pablo_l1",
      toPlatformId: "plt_neptuno_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l1_neptuno_pajaritos_inbound",
      fromPlatformId: "plt_neptuno_l1",
      toPlatformId: "plt_pajaritos_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1200,
      averageDurationSeconds: 102,
      timeProfiles: p(102),
    },
    {
      id: "seg_l1_pajaritos_las_rejas_inbound",
      fromPlatformId: "plt_pajaritos_l1",
      toPlatformId: "plt_las_rejas_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 980,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l1_las_rejas_ecuador_inbound",
      fromPlatformId: "plt_las_rejas_l1",
      toPlatformId: "plt_ecuador_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 1050,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l1_ecuador_san_alberto_inbound",
      fromPlatformId: "plt_ecuador_l1",
      toPlatformId: "plt_san_alberto_hurtado_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 920,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l1_san_alberto_usach_inbound",
      fromPlatformId: "plt_san_alberto_hurtado_l1",
      toPlatformId: "plt_universidad_de_santiago_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l1_usach_estacion_central_inbound",
      fromPlatformId: "plt_universidad_de_santiago_l1",
      toPlatformId: "plt_estacion_central_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 860,
      averageDurationSeconds: 87,
      timeProfiles: p(87),
    },
    {
      id: "seg_l1_estacion_central_union_inbound",
      fromPlatformId: "plt_estacion_central_l1",
      toPlatformId: "plt_union_latinoamericana_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 740,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l1_union_republica_inbound",
      fromPlatformId: "plt_union_latinoamericana_l1",
      toPlatformId: "plt_republica_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 820,
      averageDurationSeconds: 84,
      timeProfiles: p(84),
    },
    {
      id: "seg_l1_republica_los_heroes_inbound",
      fromPlatformId: "plt_republica_l1",
      toPlatformId: "plt_los_heroes_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 900,
      averageDurationSeconds: 91,
      timeProfiles: p(91),
    },
    {
      id: "seg_l1_los_heroes_la_moneda_inbound",
      fromPlatformId: "plt_los_heroes_l1",
      toPlatformId: "plt_la_moneda_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 760,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l1_la_moneda_uch_inbound",
      fromPlatformId: "plt_la_moneda_l1",
      toPlatformId: "plt_universidad_de_chile_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 680,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_l1_uch_santa_lucia_inbound",
      fromPlatformId: "plt_universidad_de_chile_l1",
      toPlatformId: "plt_santa_lucia_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 720,
      averageDurationSeconds: 78,
      timeProfiles: p(78),
    },
    {
      id: "seg_l1_santa_lucia_ucatolica_inbound",
      fromPlatformId: "plt_santa_lucia_l1",
      toPlatformId: "plt_universidad_catolica_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 640,
      averageDurationSeconds: 72,
      timeProfiles: p(72),
    },
    {
      id: "seg_l1_ucatolica_baquedano_inbound",
      fromPlatformId: "plt_universidad_catolica_l1",
      toPlatformId: "plt_baquedano_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 680,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_l1_baquedano_salvador_inbound",
      fromPlatformId: "plt_baquedano_l1",
      toPlatformId: "plt_salvador_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 860,
      averageDurationSeconds: 87,
      timeProfiles: p(87),
    },
    {
      id: "seg_l1_salvador_manuel_montt_inbound",
      fromPlatformId: "plt_salvador_l1",
      toPlatformId: "plt_manuel_montt_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 17,
      distanceMeters: 950,
      averageDurationSeconds: 93,
      timeProfiles: p(93),
    },
    {
      id: "seg_l1_manuel_montt_pedro_valdivia_inbound",
      fromPlatformId: "plt_manuel_montt_l1",
      toPlatformId: "plt_pedro_de_valdivia_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 18,
      distanceMeters: 870,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l1_pedro_valdivia_los_leones_inbound",
      fromPlatformId: "plt_pedro_de_valdivia_l1",
      toPlatformId: "plt_los_leones_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 19,
      distanceMeters: 820,
      averageDurationSeconds: 84,
      timeProfiles: p(84),
    },
    {
      id: "seg_l1_los_leones_tobalaba_inbound",
      fromPlatformId: "plt_los_leones_l1",
      toPlatformId: "plt_tobalaba_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 20,
      distanceMeters: 980,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l1_tobalaba_el_golf_inbound",
      fromPlatformId: "plt_tobalaba_l1",
      toPlatformId: "plt_el_golf_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 21,
      distanceMeters: 1380,
      averageDurationSeconds: 118,
      timeProfiles: p(118),
    },
    {
      id: "seg_l1_el_golf_alcantara_inbound",
      fromPlatformId: "plt_el_golf_l1",
      toPlatformId: "plt_alcantara_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 22,
      distanceMeters: 1020,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l1_alcantara_escuela_militar_inbound",
      fromPlatformId: "plt_alcantara_l1",
      toPlatformId: "plt_escuela_militar_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 23,
      distanceMeters: 1280,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l1_escuela_militar_manquehue_inbound",
      fromPlatformId: "plt_escuela_militar_l1",
      toPlatformId: "plt_manquehue_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 24,
      distanceMeters: 740,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l1_manquehue_hernando_inbound",
      fromPlatformId: "plt_manquehue_l1",
      toPlatformId: "plt_hernando_de_magallanes_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 25,
      distanceMeters: 680,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_l1_hernando_los_dominicos_inbound",
      fromPlatformId: "plt_hernando_de_magallanes_l1",
      toPlatformId: "plt_los_dominicos_l1",
      lineId: "L1",
      direction: "INBOUND",
      sequence: 26,
      distanceMeters: 620,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
    {
      id: "seg_l1_neptuno_san_pablo_outbound",
      fromPlatformId: "plt_neptuno_l1",
      toPlatformId: "plt_san_pablo_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 1,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l1_pajaritos_neptuno_outbound",
      fromPlatformId: "plt_pajaritos_l1",
      toPlatformId: "plt_neptuno_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 2,
      distanceMeters: 1200,
      averageDurationSeconds: 102,
      timeProfiles: p(102),
    },
    {
      id: "seg_l1_las_rejas_pajaritos_outbound",
      fromPlatformId: "plt_las_rejas_l1",
      toPlatformId: "plt_pajaritos_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 3,
      distanceMeters: 980,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l1_ecuador_las_rejas_outbound",
      fromPlatformId: "plt_ecuador_l1",
      toPlatformId: "plt_las_rejas_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 4,
      distanceMeters: 1050,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l1_san_alberto_ecuador_outbound",
      fromPlatformId: "plt_san_alberto_hurtado_l1",
      toPlatformId: "plt_ecuador_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 5,
      distanceMeters: 920,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l1_usach_san_alberto_outbound",
      fromPlatformId: "plt_universidad_de_santiago_l1",
      toPlatformId: "plt_san_alberto_hurtado_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 6,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l1_estacion_central_usach_outbound",
      fromPlatformId: "plt_estacion_central_l1",
      toPlatformId: "plt_universidad_de_santiago_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 7,
      distanceMeters: 860,
      averageDurationSeconds: 87,
      timeProfiles: p(87),
    },
    {
      id: "seg_l1_union_estacion_central_outbound",
      fromPlatformId: "plt_union_latinoamericana_l1",
      toPlatformId: "plt_estacion_central_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 8,
      distanceMeters: 740,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l1_republica_union_outbound",
      fromPlatformId: "plt_republica_l1",
      toPlatformId: "plt_union_latinoamericana_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 9,
      distanceMeters: 820,
      averageDurationSeconds: 84,
      timeProfiles: p(84),
    },
    {
      id: "seg_l1_los_heroes_republica_outbound",
      fromPlatformId: "plt_los_heroes_l1",
      toPlatformId: "plt_republica_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 10,
      distanceMeters: 900,
      averageDurationSeconds: 91,
      timeProfiles: p(91),
    },
    {
      id: "seg_l1_la_moneda_los_heroes_outbound",
      fromPlatformId: "plt_la_moneda_l1",
      toPlatformId: "plt_los_heroes_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 11,
      distanceMeters: 760,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l1_uch_la_moneda_outbound",
      fromPlatformId: "plt_universidad_de_chile_l1",
      toPlatformId: "plt_la_moneda_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 12,
      distanceMeters: 680,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_l1_santa_lucia_uch_outbound",
      fromPlatformId: "plt_santa_lucia_l1",
      toPlatformId: "plt_universidad_de_chile_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 13,
      distanceMeters: 720,
      averageDurationSeconds: 78,
      timeProfiles: p(78),
    },
    {
      id: "seg_l1_ucatolica_santa_lucia_outbound",
      fromPlatformId: "plt_universidad_catolica_l1",
      toPlatformId: "plt_santa_lucia_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 14,
      distanceMeters: 640,
      averageDurationSeconds: 72,
      timeProfiles: p(72),
    },
    {
      id: "seg_l1_baquedano_ucatolica_outbound",
      fromPlatformId: "plt_baquedano_l1",
      toPlatformId: "plt_universidad_catolica_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 15,
      distanceMeters: 680,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_l1_salvador_baquedano_outbound",
      fromPlatformId: "plt_salvador_l1",
      toPlatformId: "plt_baquedano_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 16,
      distanceMeters: 860,
      averageDurationSeconds: 87,
      timeProfiles: p(87),
    },
    {
      id: "seg_l1_manuel_montt_salvador_outbound",
      fromPlatformId: "plt_manuel_montt_l1",
      toPlatformId: "plt_salvador_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 17,
      distanceMeters: 950,
      averageDurationSeconds: 93,
      timeProfiles: p(93),
    },
    {
      id: "seg_l1_pedro_valdivia_manuel_montt_outbound",
      fromPlatformId: "plt_pedro_de_valdivia_l1",
      toPlatformId: "plt_manuel_montt_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 18,
      distanceMeters: 870,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l1_los_leones_pedro_valdivia_outbound",
      fromPlatformId: "plt_los_leones_l1",
      toPlatformId: "plt_pedro_de_valdivia_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 19,
      distanceMeters: 820,
      averageDurationSeconds: 84,
      timeProfiles: p(84),
    },
    {
      id: "seg_l1_tobalaba_los_leones_outbound",
      fromPlatformId: "plt_tobalaba_l1",
      toPlatformId: "plt_los_leones_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 20,
      distanceMeters: 980,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l1_el_golf_tobalaba_outbound",
      fromPlatformId: "plt_el_golf_l1",
      toPlatformId: "plt_tobalaba_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 21,
      distanceMeters: 1380,
      averageDurationSeconds: 118,
      timeProfiles: p(118),
    },
    {
      id: "seg_l1_alcantara_el_golf_outbound",
      fromPlatformId: "plt_alcantara_l1",
      toPlatformId: "plt_el_golf_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 22,
      distanceMeters: 1020,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l1_escuela_militar_alcantara_outbound",
      fromPlatformId: "plt_escuela_militar_l1",
      toPlatformId: "plt_alcantara_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 23,
      distanceMeters: 1280,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l1_manquehue_escuela_militar_outbound",
      fromPlatformId: "plt_manquehue_l1",
      toPlatformId: "plt_escuela_militar_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 24,
      distanceMeters: 740,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l1_hernando_manquehue_outbound",
      fromPlatformId: "plt_hernando_de_magallanes_l1",
      toPlatformId: "plt_manquehue_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 25,
      distanceMeters: 680,
      averageDurationSeconds: 75,
      timeProfiles: p(75),
    },
    {
      id: "seg_l1_los_dominicos_hernando_outbound",
      fromPlatformId: "plt_los_dominicos_l1",
      toPlatformId: "plt_hernando_de_magallanes_l1",
      lineId: "L1",
      direction: "OUTBOUND",
      sequence: 26,
      distanceMeters: 620,
      averageDurationSeconds: 70,
      timeProfiles: p(70),
    },
  ],
};
