import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 25200,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const L2: LineDefinition = {
  line: { id: "L2", name: "Línea 2", color: "#F8C300" },
  platforms: [
    {
      id: "plt_hospital_el_pino_l2",
      stationId: "st_hospital_el_pino",
      lineId: "L2",
    },
    {
      id: "plt_copa_lo_martinez_l2",
      stationId: "st_copa_lo_martinez",
      lineId: "L2",
    },
    { id: "plt_observatorio_l2", stationId: "st_observatorio", lineId: "L2" },
    { id: "plt_el_bosque_l2", stationId: "st_el_bosque", lineId: "L2" },
    { id: "plt_la_cisterna_l2", stationId: "st_la_cisterna", lineId: "L2" },
    { id: "plt_el_parron_l2", stationId: "st_el_parron", lineId: "L2" },
    { id: "plt_lo_ovalle_l2", stationId: "st_lo_ovalle", lineId: "L2" },
    {
      id: "plt_ciudad_del_nino_l2",
      stationId: "st_ciudad_del_nino",
      lineId: "L2",
    },
    { id: "plt_departamental_l2", stationId: "st_departamental", lineId: "L2" },
    { id: "plt_lo_vial_l2", stationId: "st_lo_vial", lineId: "L2" },
    { id: "plt_san_miguel_l2", stationId: "st_san_miguel", lineId: "L2" },
    { id: "plt_el_llano_l2", stationId: "st_el_llano", lineId: "L2" },
    { id: "plt_franklin_l2", stationId: "st_franklin", lineId: "L2" },
    { id: "plt_rondizzoni_l2", stationId: "st_rondizzoni", lineId: "L2" },
    {
      id: "plt_parque_ohiggins_l2",
      stationId: "st_parque_ohiggins",
      lineId: "L2",
    },
    { id: "plt_toesca_l2", stationId: "st_toesca", lineId: "L2" },
    { id: "plt_los_heroes_l2", stationId: "st_los_heroes", lineId: "L2" },
    { id: "plt_santa_ana_l2", stationId: "st_santa_ana", lineId: "L2" },
    {
      id: "plt_puente_cal_y_canto_l2",
      stationId: "st_puente_cal_y_canto",
      lineId: "L2",
    },
    { id: "plt_patronato_l2", stationId: "st_patronato", lineId: "L2" },
    { id: "plt_cerro_blanco_l2", stationId: "st_cerro_blanco", lineId: "L2" },
    { id: "plt_cementerios_l2", stationId: "st_cementerios", lineId: "L2" },
    { id: "plt_einstein_l2", stationId: "st_einstein", lineId: "L2" },
    { id: "plt_dorsal_l2", stationId: "st_dorsal", lineId: "L2" },
    { id: "plt_zapadores_l2", stationId: "st_zapadores", lineId: "L2" },
    {
      id: "plt_vespucio_norte_l2",
      stationId: "st_vespucio_norte",
      lineId: "L2",
    },
  ],
  segments: [
    {
      id: "seg_l2_la_cisterna_el_parron_inbound",
      fromPlatformId: "plt_la_cisterna_l2",
      toPlatformId: "plt_el_parron_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_el_parron_lo_ovalle_inbound",
      fromPlatformId: "plt_el_parron_l2",
      toPlatformId: "plt_lo_ovalle_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_lo_ovalle_ciudad_del_nino_inbound",
      fromPlatformId: "plt_lo_ovalle_l2",
      toPlatformId: "plt_ciudad_del_nino_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l2_ciudad_del_nino_departamental_inbound",
      fromPlatformId: "plt_ciudad_del_nino_l2",
      toPlatformId: "plt_departamental_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_departamental_lo_vial_inbound",
      fromPlatformId: "plt_departamental_l2",
      toPlatformId: "plt_lo_vial_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_lo_vial_san_miguel_inbound",
      fromPlatformId: "plt_lo_vial_l2",
      toPlatformId: "plt_san_miguel_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_san_miguel_el_llano_inbound",
      fromPlatformId: "plt_san_miguel_l2",
      toPlatformId: "plt_el_llano_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l2_el_llano_franklin_inbound",
      fromPlatformId: "plt_el_llano_l2",
      toPlatformId: "plt_franklin_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_franklin_rondizzoni_inbound",
      fromPlatformId: "plt_franklin_l2",
      toPlatformId: "plt_rondizzoni_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_rondizzoni_parque_ohiggins_inbound",
      fromPlatformId: "plt_rondizzoni_l2",
      toPlatformId: "plt_parque_ohiggins_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 950,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l2_parque_ohiggins_toesca_inbound",
      fromPlatformId: "plt_parque_ohiggins_l2",
      toPlatformId: "plt_toesca_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 1000,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l2_toesca_los_heroes_inbound",
      fromPlatformId: "plt_toesca_l2",
      toPlatformId: "plt_los_heroes_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l2_los_heroes_santa_ana_inbound",
      fromPlatformId: "plt_los_heroes_l2",
      toPlatformId: "plt_santa_ana_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_santa_ana_puente_inbound",
      fromPlatformId: "plt_santa_ana_l2",
      toPlatformId: "plt_puente_cal_y_canto_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_puente_patronato_inbound",
      fromPlatformId: "plt_puente_cal_y_canto_l2",
      toPlatformId: "plt_patronato_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l2_patronato_cerro_blanco_inbound",
      fromPlatformId: "plt_patronato_l2",
      toPlatformId: "plt_cerro_blanco_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_cerro_blanco_cementerios_inbound",
      fromPlatformId: "plt_cerro_blanco_l2",
      toPlatformId: "plt_cementerios_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 17,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_cementerios_einstein_inbound",
      fromPlatformId: "plt_cementerios_l2",
      toPlatformId: "plt_einstein_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 18,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_einstein_dorsal_inbound",
      fromPlatformId: "plt_einstein_l2",
      toPlatformId: "plt_dorsal_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 19,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_dorsal_zapadores_inbound",
      fromPlatformId: "plt_dorsal_l2",
      toPlatformId: "plt_zapadores_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 20,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_zapadores_vespucio_norte_inbound",
      fromPlatformId: "plt_zapadores_l2",
      toPlatformId: "plt_vespucio_norte_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 21,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_el_parron_la_cisterna_outbound",
      fromPlatformId: "plt_el_parron_l2",
      toPlatformId: "plt_la_cisterna_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 1,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_lo_ovalle_el_parron_outbound",
      fromPlatformId: "plt_lo_ovalle_l2",
      toPlatformId: "plt_el_parron_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 2,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_ciudad_del_nino_lo_ovalle_outbound",
      fromPlatformId: "plt_ciudad_del_nino_l2",
      toPlatformId: "plt_lo_ovalle_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 3,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l2_departamental_ciudad_del_nino_outbound",
      fromPlatformId: "plt_departamental_l2",
      toPlatformId: "plt_ciudad_del_nino_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 4,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_lo_vial_departamental_outbound",
      fromPlatformId: "plt_lo_vial_l2",
      toPlatformId: "plt_departamental_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 5,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_san_miguel_lo_vial_outbound",
      fromPlatformId: "plt_san_miguel_l2",
      toPlatformId: "plt_lo_vial_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 6,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_el_llano_san_miguel_outbound",
      fromPlatformId: "plt_el_llano_l2",
      toPlatformId: "plt_san_miguel_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 7,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l2_franklin_el_llano_outbound",
      fromPlatformId: "plt_franklin_l2",
      toPlatformId: "plt_el_llano_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 8,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_rondizzoni_franklin_outbound",
      fromPlatformId: "plt_rondizzoni_l2",
      toPlatformId: "plt_franklin_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 9,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_parque_ohiggins_rondizzoni_outbound",
      fromPlatformId: "plt_parque_ohiggins_l2",
      toPlatformId: "plt_rondizzoni_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 10,
      distanceMeters: 950,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l2_toesca_parque_ohiggins_outbound",
      fromPlatformId: "plt_toesca_l2",
      toPlatformId: "plt_parque_ohiggins_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 11,
      distanceMeters: 1000,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l2_los_heroes_toesca_outbound",
      fromPlatformId: "plt_los_heroes_l2",
      toPlatformId: "plt_toesca_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 12,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l2_santa_ana_los_heroes_outbound",
      fromPlatformId: "plt_santa_ana_l2",
      toPlatformId: "plt_los_heroes_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 13,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_puente_santa_ana_outbound",
      fromPlatformId: "plt_puente_cal_y_canto_l2",
      toPlatformId: "plt_santa_ana_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 14,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_patronato_puente_outbound",
      fromPlatformId: "plt_patronato_l2",
      toPlatformId: "plt_puente_cal_y_canto_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 15,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l2_cerro_blanco_patronato_outbound",
      fromPlatformId: "plt_cerro_blanco_l2",
      toPlatformId: "plt_patronato_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 16,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_cementerios_cerro_blanco_outbound",
      fromPlatformId: "plt_cementerios_l2",
      toPlatformId: "plt_cerro_blanco_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 17,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_einstein_cementerios_outbound",
      fromPlatformId: "plt_einstein_l2",
      toPlatformId: "plt_cementerios_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 18,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l2_dorsal_einstein_outbound",
      fromPlatformId: "plt_dorsal_l2",
      toPlatformId: "plt_einstein_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 19,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l2_zapadores_dorsal_outbound",
      fromPlatformId: "plt_zapadores_l2",
      toPlatformId: "plt_dorsal_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 20,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l2_vespucio_norte_zapadores_outbound",
      fromPlatformId: "plt_vespucio_norte_l2",
      toPlatformId: "plt_zapadores_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 21,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    // Extensão sul L2 — INBOUND (Hospital El Pino → Vespucio Norte)
    {
      id: "seg_l2_hospital_el_pino_copa_lo_martinez_inbound",
      fromPlatformId: "plt_hospital_el_pino_l2",
      toPlatformId: "plt_copa_lo_martinez_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 102,
      timeProfiles: p(102),
    },
    {
      id: "seg_l2_copa_lo_martinez_observatorio_inbound",
      fromPlatformId: "plt_copa_lo_martinez_l2",
      toPlatformId: "plt_observatorio_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 980,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l2_observatorio_el_bosque_inbound",
      fromPlatformId: "plt_observatorio_l2",
      toPlatformId: "plt_el_bosque_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 920,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l2_el_bosque_la_cisterna_inbound",
      fromPlatformId: "plt_el_bosque_l2",
      toPlatformId: "plt_la_cisterna_l2",
      lineId: "L2",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 880,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    // Extensão sul L2 — OUTBOUND (Vespucio Norte → Hospital El Pino)
    {
      id: "seg_l2_la_cisterna_el_bosque_outbound",
      fromPlatformId: "plt_la_cisterna_l2",
      toPlatformId: "plt_el_bosque_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 22,
      distanceMeters: 880,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l2_el_bosque_observatorio_outbound",
      fromPlatformId: "plt_el_bosque_l2",
      toPlatformId: "plt_observatorio_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 23,
      distanceMeters: 920,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l2_observatorio_copa_lo_martinez_outbound",
      fromPlatformId: "plt_observatorio_l2",
      toPlatformId: "plt_copa_lo_martinez_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 24,
      distanceMeters: 980,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l2_copa_lo_martinez_hospital_el_pino_outbound",
      fromPlatformId: "plt_copa_lo_martinez_l2",
      toPlatformId: "plt_hospital_el_pino_l2",
      lineId: "L2",
      direction: "OUTBOUND",
      sequence: 25,
      distanceMeters: 1100,
      averageDurationSeconds: 102,
      timeProfiles: p(102),
    },
  ],
};
