import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 25200,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const L3: LineDefinition = {
  line: { id: "L3", name: "Línea 3", color: "#9B5A28" },
  platforms: [
    {
      id: "plt_los_libertadores_l3",
      stationId: "st_los_libertadores",
      lineId: "L3",
    },
    { id: "plt_cardenal_caro_l3", stationId: "st_cardenal_caro", lineId: "L3" },
    { id: "plt_vivaceta_l3", stationId: "st_vivaceta", lineId: "L3" },
    { id: "plt_conchali_l3", stationId: "st_conchali", lineId: "L3" },
    {
      id: "plt_plaza_chacabuco_l3",
      stationId: "st_plaza_chacabuco",
      lineId: "L3",
    },
    { id: "plt_hospitales_l3", stationId: "st_hospitales", lineId: "L3" },
    {
      id: "plt_puente_cal_y_canto_l3",
      stationId: "st_puente_cal_y_canto",
      lineId: "L3",
    },
    {
      id: "plt_plaza_de_armas_l3",
      stationId: "st_plaza_de_armas",
      lineId: "L3",
    },
    {
      id: "plt_universidad_de_chile_l3",
      stationId: "st_universidad_de_chile",
      lineId: "L3",
    },
    {
      id: "plt_parque_almagro_l3",
      stationId: "st_parque_almagro",
      lineId: "L3",
    },
    { id: "plt_matta_l3", stationId: "st_matta", lineId: "L3" },
    { id: "plt_irarrazaval_l3", stationId: "st_irarrazaval", lineId: "L3" },
    {
      id: "plt_monsenor_eyzaguirre_l3",
      stationId: "st_monsenor_eyzaguirre",
      lineId: "L3",
    },
    { id: "plt_nunoa_l3", stationId: "st_nunoa", lineId: "L3" },
    { id: "plt_chile_espana_l3", stationId: "st_chile_espana", lineId: "L3" },
    { id: "plt_villa_frei_l3", stationId: "st_villa_frei", lineId: "L3" },
    { id: "plt_plaza_egana_l3", stationId: "st_plaza_egana", lineId: "L3" },
    {
      id: "plt_fernando_castillo_velasco_l3",
      stationId: "st_fernando_castillo_velasco",
      lineId: "L3",
    },
  ],
  segments: [
    {
      id: "seg_l3_los_libertadores_cardenal_caro_inbound",
      fromPlatformId: "plt_los_libertadores_l3",
      toPlatformId: "plt_cardenal_caro_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 880,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l3_cardenal_caro_vivaceta_inbound",
      fromPlatformId: "plt_cardenal_caro_l3",
      toPlatformId: "plt_vivaceta_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 820,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l3_vivaceta_conchali_inbound",
      fromPlatformId: "plt_vivaceta_l3",
      toPlatformId: "plt_conchali_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l3_conchali_plaza_chacabuco_inbound",
      fromPlatformId: "plt_conchali_l3",
      toPlatformId: "plt_plaza_chacabuco_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l3_plaza_chacabuco_hospitales_inbound",
      fromPlatformId: "plt_plaza_chacabuco_l3",
      toPlatformId: "plt_hospitales_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l3_hospitales_puente_inbound",
      fromPlatformId: "plt_hospitales_l3",
      toPlatformId: "plt_puente_cal_y_canto_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 950,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l3_puente_plaza_de_armas_inbound",
      fromPlatformId: "plt_puente_cal_y_canto_l3",
      toPlatformId: "plt_plaza_de_armas_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 820,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l3_plaza_de_armas_uch_inbound",
      fromPlatformId: "plt_plaza_de_armas_l3",
      toPlatformId: "plt_universidad_de_chile_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 760,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l3_uch_parque_almagro_inbound",
      fromPlatformId: "plt_universidad_de_chile_l3",
      toPlatformId: "plt_parque_almagro_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 840,
      averageDurationSeconds: 87,
      timeProfiles: p(87),
    },
    {
      id: "seg_l3_parque_almagro_matta_inbound",
      fromPlatformId: "plt_parque_almagro_l3",
      toPlatformId: "plt_matta_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l3_matta_irarrazaval_inbound",
      fromPlatformId: "plt_matta_l3",
      toPlatformId: "plt_irarrazaval_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l3_irarrazaval_monsenor_inbound",
      fromPlatformId: "plt_irarrazaval_l3",
      toPlatformId: "plt_monsenor_eyzaguirre_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 920,
      averageDurationSeconds: 93,
      timeProfiles: p(93),
    },
    {
      id: "seg_l3_monsenor_nunoa_inbound",
      fromPlatformId: "plt_monsenor_eyzaguirre_l3",
      toPlatformId: "plt_nunoa_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l3_nunoa_chile_espana_inbound",
      fromPlatformId: "plt_nunoa_l3",
      toPlatformId: "plt_chile_espana_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 860,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l3_chile_espana_villa_frei_inbound",
      fromPlatformId: "plt_chile_espana_l3",
      toPlatformId: "plt_villa_frei_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 820,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l3_villa_frei_plaza_egana_inbound",
      fromPlatformId: "plt_villa_frei_l3",
      toPlatformId: "plt_plaza_egana_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l3_plaza_egana_fernando_castillo_inbound",
      fromPlatformId: "plt_plaza_egana_l3",
      toPlatformId: "plt_fernando_castillo_velasco_l3",
      lineId: "L3",
      direction: "INBOUND",
      sequence: 17,
      distanceMeters: 740,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l3_cardenal_caro_los_libertadores_outbound",
      fromPlatformId: "plt_cardenal_caro_l3",
      toPlatformId: "plt_los_libertadores_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 1,
      distanceMeters: 880,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l3_vivaceta_cardenal_caro_outbound",
      fromPlatformId: "plt_vivaceta_l3",
      toPlatformId: "plt_cardenal_caro_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 2,
      distanceMeters: 820,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l3_conchali_vivaceta_outbound",
      fromPlatformId: "plt_conchali_l3",
      toPlatformId: "plt_vivaceta_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 3,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l3_plaza_chacabuco_conchali_outbound",
      fromPlatformId: "plt_plaza_chacabuco_l3",
      toPlatformId: "plt_conchali_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 4,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l3_hospitales_plaza_chacabuco_outbound",
      fromPlatformId: "plt_hospitales_l3",
      toPlatformId: "plt_plaza_chacabuco_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 5,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l3_puente_hospitales_outbound",
      fromPlatformId: "plt_puente_cal_y_canto_l3",
      toPlatformId: "plt_hospitales_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 6,
      distanceMeters: 950,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l3_plaza_de_armas_puente_outbound",
      fromPlatformId: "plt_plaza_de_armas_l3",
      toPlatformId: "plt_puente_cal_y_canto_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 7,
      distanceMeters: 820,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l3_uch_plaza_de_armas_outbound",
      fromPlatformId: "plt_universidad_de_chile_l3",
      toPlatformId: "plt_plaza_de_armas_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 8,
      distanceMeters: 760,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l3_parque_almagro_uch_outbound",
      fromPlatformId: "plt_parque_almagro_l3",
      toPlatformId: "plt_universidad_de_chile_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 9,
      distanceMeters: 840,
      averageDurationSeconds: 87,
      timeProfiles: p(87),
    },
    {
      id: "seg_l3_matta_parque_almagro_outbound",
      fromPlatformId: "plt_matta_l3",
      toPlatformId: "plt_parque_almagro_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 10,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l3_irarrazaval_matta_outbound",
      fromPlatformId: "plt_irarrazaval_l3",
      toPlatformId: "plt_matta_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 11,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l3_monsenor_irarrazaval_outbound",
      fromPlatformId: "plt_monsenor_eyzaguirre_l3",
      toPlatformId: "plt_irarrazaval_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 12,
      distanceMeters: 920,
      averageDurationSeconds: 93,
      timeProfiles: p(93),
    },
    {
      id: "seg_l3_nunoa_monsenor_outbound",
      fromPlatformId: "plt_nunoa_l3",
      toPlatformId: "plt_monsenor_eyzaguirre_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 13,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l3_chile_espana_nunoa_outbound",
      fromPlatformId: "plt_chile_espana_l3",
      toPlatformId: "plt_nunoa_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 14,
      distanceMeters: 860,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l3_villa_frei_chile_espana_outbound",
      fromPlatformId: "plt_villa_frei_l3",
      toPlatformId: "plt_chile_espana_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 15,
      distanceMeters: 820,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l3_plaza_egana_villa_frei_outbound",
      fromPlatformId: "plt_plaza_egana_l3",
      toPlatformId: "plt_villa_frei_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 16,
      distanceMeters: 780,
      averageDurationSeconds: 82,
      timeProfiles: p(82),
    },
    {
      id: "seg_l3_fernando_castillo_plaza_egana_outbound",
      fromPlatformId: "plt_fernando_castillo_velasco_l3",
      toPlatformId: "plt_plaza_egana_l3",
      lineId: "L3",
      direction: "OUTBOUND",
      sequence: 17,
      distanceMeters: 740,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
  ],
};
