import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 25200,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const L4: LineDefinition = {
  line: { id: "L4", name: "Línea 4", color: "#1E4C9A" },
  platforms: [
    { id: "plt_tobalaba_l4", stationId: "st_tobalaba", lineId: "L4" },
    {
      id: "plt_cristobal_colon_l4",
      stationId: "st_cristobal_colon",
      lineId: "L4",
    },
    {
      id: "plt_francisco_bilbao_l4",
      stationId: "st_francisco_bilbao",
      lineId: "L4",
    },
    {
      id: "plt_principe_de_gales_l4",
      stationId: "st_principe_de_gales",
      lineId: "L4",
    },
    { id: "plt_simon_bolivar_l4", stationId: "st_simon_bolivar", lineId: "L4" },
    { id: "plt_plaza_egana_l4", stationId: "st_plaza_egana", lineId: "L4" },
    {
      id: "plt_los_orientales_l4",
      stationId: "st_los_orientales",
      lineId: "L4",
    },
    { id: "plt_grecia_l4", stationId: "st_grecia", lineId: "L4" },
    {
      id: "plt_los_presidentes_l4",
      stationId: "st_los_presidentes",
      lineId: "L4",
    },
    { id: "plt_quilin_l4", stationId: "st_quilin", lineId: "L4" },
    { id: "plt_las_torres_l4", stationId: "st_las_torres", lineId: "L4" },
    { id: "plt_macul_l4", stationId: "st_macul", lineId: "L4" },
    {
      id: "plt_vicuna_mackenna_l4",
      stationId: "st_vicuna_mackenna",
      lineId: "L4",
    },
    {
      id: "plt_vicente_valdes_l4",
      stationId: "st_vicente_valdes",
      lineId: "L4",
    },
    {
      id: "plt_rojas_magallanes_l4",
      stationId: "st_rojas_magallanes",
      lineId: "L4",
    },
    { id: "plt_trinidad_l4", stationId: "st_trinidad", lineId: "L4" },
    {
      id: "plt_san_jose_de_la_estrella_l4",
      stationId: "st_san_jose_de_la_estrella",
      lineId: "L4",
    },
    { id: "plt_los_quillayes_l4", stationId: "st_los_quillayes", lineId: "L4" },
    { id: "plt_elisa_correa_l4", stationId: "st_elisa_correa", lineId: "L4" },
    {
      id: "plt_hospital_sotero_del_rio_l4",
      stationId: "st_hospital_sotero_del_rio",
      lineId: "L4",
    },
    {
      id: "plt_protectora_de_la_infancia_l4",
      stationId: "st_protectora_de_la_infancia",
      lineId: "L4",
    },
    { id: "plt_las_mercedes_l4", stationId: "st_las_mercedes", lineId: "L4" },
    {
      id: "plt_plaza_de_puente_alto_l4",
      stationId: "st_plaza_de_puente_alto",
      lineId: "L4",
    },
  ],
  segments: [
    {
      id: "seg_l4_tobalaba_cristobal_colon_inbound",
      fromPlatformId: "plt_tobalaba_l4",
      toPlatformId: "plt_cristobal_colon_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l4_cristobal_colon_francisco_bilbao_inbound",
      fromPlatformId: "plt_cristobal_colon_l4",
      toPlatformId: "plt_francisco_bilbao_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_francisco_bilbao_principe_inbound",
      fromPlatformId: "plt_francisco_bilbao_l4",
      toPlatformId: "plt_principe_de_gales_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l4_principe_simon_bolivar_inbound",
      fromPlatformId: "plt_principe_de_gales_l4",
      toPlatformId: "plt_simon_bolivar_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 980,
      averageDurationSeconds: 96,
      timeProfiles: p(96),
    },
    {
      id: "seg_l4_simon_bolivar_plaza_egana_inbound",
      fromPlatformId: "plt_simon_bolivar_l4",
      toPlatformId: "plt_plaza_egana_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 880,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l4_plaza_egana_los_orientales_inbound",
      fromPlatformId: "plt_plaza_egana_l4",
      toPlatformId: "plt_los_orientales_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_los_orientales_grecia_inbound",
      fromPlatformId: "plt_los_orientales_l4",
      toPlatformId: "plt_grecia_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l4_grecia_los_presidentes_inbound",
      fromPlatformId: "plt_grecia_l4",
      toPlatformId: "plt_los_presidentes_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l4_los_presidentes_quilin_inbound",
      fromPlatformId: "plt_los_presidentes_l4",
      toPlatformId: "plt_quilin_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l4_quilin_las_torres_inbound",
      fromPlatformId: "plt_quilin_l4",
      toPlatformId: "plt_las_torres_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_las_torres_macul_inbound",
      fromPlatformId: "plt_las_torres_l4",
      toPlatformId: "plt_macul_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l4_macul_vicuna_mackenna_inbound",
      fromPlatformId: "plt_macul_l4",
      toPlatformId: "plt_vicuna_mackenna_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 1800,
      averageDurationSeconds: 140,
      timeProfiles: p(140),
    },
    {
      id: "seg_l4_vicuna_mackenna_vicente_valdes_inbound",
      fromPlatformId: "plt_vicuna_mackenna_l4",
      toPlatformId: "plt_vicente_valdes_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 3800,
      averageDurationSeconds: 240,
      timeProfiles: p(240),
    },
    {
      id: "seg_l4_vicente_valdes_rojas_magallanes_inbound",
      fromPlatformId: "plt_vicente_valdes_l4",
      toPlatformId: "plt_rojas_magallanes_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l4_rojas_magallanes_trinidad_inbound",
      fromPlatformId: "plt_rojas_magallanes_l4",
      toPlatformId: "plt_trinidad_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_trinidad_san_jose_inbound",
      fromPlatformId: "plt_trinidad_l4",
      toPlatformId: "plt_san_jose_de_la_estrella_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 880,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l4_san_jose_los_quillayes_inbound",
      fromPlatformId: "plt_san_jose_de_la_estrella_l4",
      toPlatformId: "plt_los_quillayes_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 17,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_los_quillayes_elisa_correa_inbound",
      fromPlatformId: "plt_los_quillayes_l4",
      toPlatformId: "plt_elisa_correa_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 18,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l4_elisa_correa_hospital_sotero_inbound",
      fromPlatformId: "plt_elisa_correa_l4",
      toPlatformId: "plt_hospital_sotero_del_rio_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 19,
      distanceMeters: 720,
      averageDurationSeconds: 78,
      timeProfiles: p(78),
    },
    {
      id: "seg_l4_hospital_sotero_protectora_inbound",
      fromPlatformId: "plt_hospital_sotero_del_rio_l4",
      toPlatformId: "plt_protectora_de_la_infancia_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 20,
      distanceMeters: 680,
      averageDurationSeconds: 74,
      timeProfiles: p(74),
    },
    {
      id: "seg_l4_protectora_las_mercedes_inbound",
      fromPlatformId: "plt_protectora_de_la_infancia_l4",
      toPlatformId: "plt_las_mercedes_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 21,
      distanceMeters: 640,
      averageDurationSeconds: 72,
      timeProfiles: p(72),
    },
    {
      id: "seg_l4_las_mercedes_plaza_puente_alto_inbound",
      fromPlatformId: "plt_las_mercedes_l4",
      toPlatformId: "plt_plaza_de_puente_alto_l4",
      lineId: "L4",
      direction: "INBOUND",
      sequence: 22,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l4_cristobal_colon_tobalaba_outbound",
      fromPlatformId: "plt_cristobal_colon_l4",
      toPlatformId: "plt_tobalaba_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l4_francisco_bilbao_cristobal_colon_outbound",
      fromPlatformId: "plt_francisco_bilbao_l4",
      toPlatformId: "plt_cristobal_colon_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 2,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_principe_francisco_bilbao_outbound",
      fromPlatformId: "plt_principe_de_gales_l4",
      toPlatformId: "plt_francisco_bilbao_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 3,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l4_simon_bolivar_principe_outbound",
      fromPlatformId: "plt_simon_bolivar_l4",
      toPlatformId: "plt_principe_de_gales_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 4,
      distanceMeters: 980,
      averageDurationSeconds: 96,
      timeProfiles: p(96),
    },
    {
      id: "seg_l4_plaza_egana_simon_bolivar_outbound",
      fromPlatformId: "plt_plaza_egana_l4",
      toPlatformId: "plt_simon_bolivar_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 5,
      distanceMeters: 880,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l4_los_orientales_plaza_egana_outbound",
      fromPlatformId: "plt_los_orientales_l4",
      toPlatformId: "plt_plaza_egana_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 6,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_grecia_los_orientales_outbound",
      fromPlatformId: "plt_grecia_l4",
      toPlatformId: "plt_los_orientales_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 7,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l4_los_presidentes_grecia_outbound",
      fromPlatformId: "plt_los_presidentes_l4",
      toPlatformId: "plt_grecia_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 8,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l4_quilin_los_presidentes_outbound",
      fromPlatformId: "plt_quilin_l4",
      toPlatformId: "plt_los_presidentes_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 9,
      distanceMeters: 750,
      averageDurationSeconds: 80,
      timeProfiles: p(80),
    },
    {
      id: "seg_l4_las_torres_quilin_outbound",
      fromPlatformId: "plt_las_torres_l4",
      toPlatformId: "plt_quilin_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 10,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_macul_las_torres_outbound",
      fromPlatformId: "plt_macul_l4",
      toPlatformId: "plt_las_torres_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 11,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l4_vicuna_mackenna_macul_outbound",
      fromPlatformId: "plt_vicuna_mackenna_l4",
      toPlatformId: "plt_macul_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 12,
      distanceMeters: 1800,
      averageDurationSeconds: 140,
      timeProfiles: p(140),
    },
    {
      id: "seg_l4_vicente_valdes_vicuna_mackenna_outbound",
      fromPlatformId: "plt_vicente_valdes_l4",
      toPlatformId: "plt_vicuna_mackenna_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 13,
      distanceMeters: 3800,
      averageDurationSeconds: 240,
      timeProfiles: p(240),
    },
    {
      id: "seg_l4_rojas_magallanes_vicente_valdes_outbound",
      fromPlatformId: "plt_rojas_magallanes_l4",
      toPlatformId: "plt_vicente_valdes_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 14,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l4_trinidad_rojas_magallanes_outbound",
      fromPlatformId: "plt_trinidad_l4",
      toPlatformId: "plt_rojas_magallanes_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 15,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_san_jose_trinidad_outbound",
      fromPlatformId: "plt_san_jose_de_la_estrella_l4",
      toPlatformId: "plt_trinidad_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 16,
      distanceMeters: 880,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l4_los_quillayes_san_jose_outbound",
      fromPlatformId: "plt_los_quillayes_l4",
      toPlatformId: "plt_san_jose_de_la_estrella_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 17,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4_elisa_correa_los_quillayes_outbound",
      fromPlatformId: "plt_elisa_correa_l4",
      toPlatformId: "plt_los_quillayes_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 18,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l4_hospital_sotero_elisa_correa_outbound",
      fromPlatformId: "plt_hospital_sotero_del_rio_l4",
      toPlatformId: "plt_elisa_correa_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 19,
      distanceMeters: 720,
      averageDurationSeconds: 78,
      timeProfiles: p(78),
    },
    {
      id: "seg_l4_protectora_hospital_sotero_outbound",
      fromPlatformId: "plt_protectora_de_la_infancia_l4",
      toPlatformId: "plt_hospital_sotero_del_rio_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 20,
      distanceMeters: 680,
      averageDurationSeconds: 74,
      timeProfiles: p(74),
    },
    {
      id: "seg_l4_las_mercedes_protectora_outbound",
      fromPlatformId: "plt_las_mercedes_l4",
      toPlatformId: "plt_protectora_de_la_infancia_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 21,
      distanceMeters: 640,
      averageDurationSeconds: 72,
      timeProfiles: p(72),
    },
    {
      id: "seg_l4_plaza_puente_alto_las_mercedes_outbound",
      fromPlatformId: "plt_plaza_de_puente_alto_l4",
      toPlatformId: "plt_las_mercedes_l4",
      lineId: "L4",
      direction: "OUTBOUND",
      sequence: 22,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
  ],
};
