import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 25200,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const L4A: LineDefinition = {
  line: { id: "L4A", name: "Línea 4A", color: "#6CACE4" },
  platforms: [
    {
      id: "plt_vicuna_mackenna_l4a",
      stationId: "st_vicuna_mackenna",
      lineId: "L4A",
    },
    { id: "plt_santa_julia_l4a", stationId: "st_santa_julia", lineId: "L4A" },
    { id: "plt_la_granja_l4a", stationId: "st_la_granja", lineId: "L4A" },
    { id: "plt_santa_rosa_l4a", stationId: "st_santa_rosa", lineId: "L4A" },
    { id: "plt_san_ramon_l4a", stationId: "st_san_ramon", lineId: "L4A" },
    { id: "plt_la_cisterna_l4a", stationId: "st_la_cisterna", lineId: "L4A" },
  ],
  segments: [
    {
      id: "seg_l4a_vicuna_mackenna_santa_julia_inbound",
      fromPlatformId: "plt_vicuna_mackenna_l4a",
      toPlatformId: "plt_santa_julia_l4a",
      lineId: "L4A",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l4a_santa_julia_la_granja_inbound",
      fromPlatformId: "plt_santa_julia_l4a",
      toPlatformId: "plt_la_granja_l4a",
      lineId: "L4A",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1050,
      averageDurationSeconds: 100,
      timeProfiles: p(100),
    },
    {
      id: "seg_l4a_la_granja_santa_rosa_inbound",
      fromPlatformId: "plt_la_granja_l4a",
      toPlatformId: "plt_santa_rosa_l4a",
      lineId: "L4A",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l4a_santa_rosa_san_ramon_inbound",
      fromPlatformId: "plt_santa_rosa_l4a",
      toPlatformId: "plt_san_ramon_l4a",
      lineId: "L4A",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 980,
      averageDurationSeconds: 96,
      timeProfiles: p(96),
    },
    {
      id: "seg_l4a_san_ramon_la_cisterna_inbound",
      fromPlatformId: "plt_san_ramon_l4a",
      toPlatformId: "plt_la_cisterna_l4a",
      lineId: "L4A",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l4a_santa_julia_vicuna_mackenna_outbound",
      fromPlatformId: "plt_santa_julia_l4a",
      toPlatformId: "plt_vicuna_mackenna_l4a",
      lineId: "L4A",
      direction: "OUTBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l4a_la_granja_santa_julia_outbound",
      fromPlatformId: "plt_la_granja_l4a",
      toPlatformId: "plt_santa_julia_l4a",
      lineId: "L4A",
      direction: "OUTBOUND",
      sequence: 2,
      distanceMeters: 1050,
      averageDurationSeconds: 100,
      timeProfiles: p(100),
    },
    {
      id: "seg_l4a_santa_rosa_la_granja_outbound",
      fromPlatformId: "plt_santa_rosa_l4a",
      toPlatformId: "plt_la_granja_l4a",
      lineId: "L4A",
      direction: "OUTBOUND",
      sequence: 3,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l4a_san_ramon_santa_rosa_outbound",
      fromPlatformId: "plt_san_ramon_l4a",
      toPlatformId: "plt_santa_rosa_l4a",
      lineId: "L4A",
      direction: "OUTBOUND",
      sequence: 4,
      distanceMeters: 980,
      averageDurationSeconds: 96,
      timeProfiles: p(96),
    },
    {
      id: "seg_l4a_la_cisterna_san_ramon_outbound",
      fromPlatformId: "plt_la_cisterna_l4a",
      toPlatformId: "plt_san_ramon_l4a",
      lineId: "L4A",
      direction: "OUTBOUND",
      sequence: 5,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
  ],
};
