import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 25200,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const L5: LineDefinition = {
  line: { id: "L5", name: "Línea 5", color: "#00A650" },
  platforms: [
    {
      id: "plt_plaza_de_maipu_l5",
      stationId: "st_plaza_de_maipu",
      lineId: "L5",
    },
    {
      id: "plt_santiago_bueras_l5",
      stationId: "st_santiago_bueras",
      lineId: "L5",
    },
    { id: "plt_del_sol_l5", stationId: "st_del_sol", lineId: "L5" },
    { id: "plt_monte_tabor_l5", stationId: "st_monte_tabor", lineId: "L5" },
    { id: "plt_las_parcelas_l5", stationId: "st_las_parcelas", lineId: "L5" },
    { id: "plt_laguna_sur_l5", stationId: "st_laguna_sur", lineId: "L5" },
    { id: "plt_barrancas_l5", stationId: "st_barrancas", lineId: "L5" },
    { id: "plt_pudahuel_l5", stationId: "st_pudahuel", lineId: "L5" },
    { id: "plt_san_pablo_l5", stationId: "st_san_pablo", lineId: "L5" },
    { id: "plt_lo_prado_l5", stationId: "st_lo_prado", lineId: "L5" },
    { id: "plt_blanqueado_l5", stationId: "st_blanqueado", lineId: "L5" },
    {
      id: "plt_gruta_de_lourdes_l5",
      stationId: "st_gruta_de_lourdes",
      lineId: "L5",
    },
    { id: "plt_quinta_normal_l5", stationId: "st_quinta_normal", lineId: "L5" },
    { id: "plt_cumming_l5", stationId: "st_cumming", lineId: "L5" },
    { id: "plt_santa_ana_l5", stationId: "st_santa_ana", lineId: "L5" },
    {
      id: "plt_plaza_de_armas_l5",
      stationId: "st_plaza_de_armas",
      lineId: "L5",
    },
    { id: "plt_bellas_artes_l5", stationId: "st_bellas_artes", lineId: "L5" },
    { id: "plt_baquedano_l5", stationId: "st_baquedano", lineId: "L5" },
    {
      id: "plt_parque_bustamante_l5",
      stationId: "st_parque_bustamante",
      lineId: "L5",
    },
    { id: "plt_santa_isabel_l5", stationId: "st_santa_isabel", lineId: "L5" },
    { id: "plt_irarrazaval_l5", stationId: "st_irarrazaval", lineId: "L5" },
    { id: "plt_nuble_l5", stationId: "st_nuble", lineId: "L5" },
    {
      id: "plt_rodrigo_de_araya_l5",
      stationId: "st_rodrigo_de_araya",
      lineId: "L5",
    },
    {
      id: "plt_carlos_valdovinos_l5",
      stationId: "st_carlos_valdovinos",
      lineId: "L5",
    },
    {
      id: "plt_camino_agricola_l5",
      stationId: "st_camino_agricola",
      lineId: "L5",
    },
    { id: "plt_san_joaquin_l5", stationId: "st_san_joaquin", lineId: "L5" },
    { id: "plt_pedrero_l5", stationId: "st_pedrero", lineId: "L5" },
    { id: "plt_mirador_l5", stationId: "st_mirador", lineId: "L5" },
    {
      id: "plt_bellavista_de_la_florida_l5",
      stationId: "st_bellavista_de_la_florida",
      lineId: "L5",
    },
    {
      id: "plt_vicente_valdes_l5",
      stationId: "st_vicente_valdes",
      lineId: "L5",
    },
  ],
  segments: [
    {
      id: "seg_l5_plaza_maipu_santiago_bueras_inbound",
      fromPlatformId: "plt_plaza_de_maipu_l5",
      toPlatformId: "plt_santiago_bueras_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_santiago_bueras_del_sol_inbound",
      fromPlatformId: "plt_santiago_bueras_l5",
      toPlatformId: "plt_del_sol_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l5_del_sol_monte_tabor_inbound",
      fromPlatformId: "plt_del_sol_l5",
      toPlatformId: "plt_monte_tabor_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1150,
      averageDurationSeconds: 105,
      timeProfiles: p(105),
    },
    {
      id: "seg_l5_monte_tabor_las_parcelas_inbound",
      fromPlatformId: "plt_monte_tabor_l5",
      toPlatformId: "plt_las_parcelas_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 1300,
      averageDurationSeconds: 112,
      timeProfiles: p(112),
    },
    {
      id: "seg_l5_las_parcelas_laguna_sur_inbound",
      fromPlatformId: "plt_las_parcelas_l5",
      toPlatformId: "plt_laguna_sur_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 3200,
      averageDurationSeconds: 200,
      timeProfiles: p(200),
    },
    {
      id: "seg_l5_laguna_sur_barrancas_inbound",
      fromPlatformId: "plt_laguna_sur_l5",
      toPlatformId: "plt_barrancas_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l5_barrancas_pudahuel_inbound",
      fromPlatformId: "plt_barrancas_l5",
      toPlatformId: "plt_pudahuel_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_pudahuel_san_pablo_inbound",
      fromPlatformId: "plt_pudahuel_l5",
      toPlatformId: "plt_san_pablo_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 1300,
      averageDurationSeconds: 112,
      timeProfiles: p(112),
    },
    {
      id: "seg_l5_san_pablo_lo_prado_inbound",
      fromPlatformId: "plt_san_pablo_l5",
      toPlatformId: "plt_lo_prado_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l5_lo_prado_blanqueado_inbound",
      fromPlatformId: "plt_lo_prado_l5",
      toPlatformId: "plt_blanqueado_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 10,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l5_blanqueado_gruta_de_lourdes_inbound",
      fromPlatformId: "plt_blanqueado_l5",
      toPlatformId: "plt_gruta_de_lourdes_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 11,
      distanceMeters: 870,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l5_gruta_quinta_normal_inbound",
      fromPlatformId: "plt_gruta_de_lourdes_l5",
      toPlatformId: "plt_quinta_normal_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 12,
      distanceMeters: 1600,
      averageDurationSeconds: 125,
      timeProfiles: p(125),
    },
    {
      id: "seg_l5_quinta_normal_cumming_inbound",
      fromPlatformId: "plt_quinta_normal_l5",
      toPlatformId: "plt_cumming_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 13,
      distanceMeters: 1500,
      averageDurationSeconds: 120,
      timeProfiles: p(120),
    },
    {
      id: "seg_l5_cumming_santa_ana_inbound",
      fromPlatformId: "plt_cumming_l5",
      toPlatformId: "plt_santa_ana_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 14,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_santa_ana_plaza_de_armas_inbound",
      fromPlatformId: "plt_santa_ana_l5",
      toPlatformId: "plt_plaza_de_armas_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 15,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l5_plaza_de_armas_bellas_artes_inbound",
      fromPlatformId: "plt_plaza_de_armas_l5",
      toPlatformId: "plt_bellas_artes_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 16,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l5_bellas_artes_baquedano_inbound",
      fromPlatformId: "plt_bellas_artes_l5",
      toPlatformId: "plt_baquedano_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 17,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l5_baquedano_parque_bustamante_inbound",
      fromPlatformId: "plt_baquedano_l5",
      toPlatformId: "plt_parque_bustamante_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 18,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l5_parque_bustamante_santa_isabel_inbound",
      fromPlatformId: "plt_parque_bustamante_l5",
      toPlatformId: "plt_santa_isabel_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 19,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l5_santa_isabel_irarrazaval_inbound",
      fromPlatformId: "plt_santa_isabel_l5",
      toPlatformId: "plt_irarrazaval_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 20,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l5_irarrazaval_nuble_inbound",
      fromPlatformId: "plt_irarrazaval_l5",
      toPlatformId: "plt_nuble_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 21,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l5_nuble_rodrigo_de_araya_inbound",
      fromPlatformId: "plt_nuble_l5",
      toPlatformId: "plt_rodrigo_de_araya_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 22,
      distanceMeters: 2100,
      averageDurationSeconds: 155,
      timeProfiles: p(155),
    },
    {
      id: "seg_l5_rodrigo_carlos_valdovinos_inbound",
      fromPlatformId: "plt_rodrigo_de_araya_l5",
      toPlatformId: "plt_carlos_valdovinos_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 23,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_carlos_valdovinos_camino_agricola_inbound",
      fromPlatformId: "plt_carlos_valdovinos_l5",
      toPlatformId: "plt_camino_agricola_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 24,
      distanceMeters: 1000,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l5_camino_agricola_san_joaquin_inbound",
      fromPlatformId: "plt_camino_agricola_l5",
      toPlatformId: "plt_san_joaquin_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 25,
      distanceMeters: 950,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l5_san_joaquin_pedrero_inbound",
      fromPlatformId: "plt_san_joaquin_l5",
      toPlatformId: "plt_pedrero_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 26,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l5_pedrero_mirador_inbound",
      fromPlatformId: "plt_pedrero_l5",
      toPlatformId: "plt_mirador_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 27,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l5_mirador_bellavista_inbound",
      fromPlatformId: "plt_mirador_l5",
      toPlatformId: "plt_bellavista_de_la_florida_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 28,
      distanceMeters: 1000,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l5_bellavista_vicente_valdes_inbound",
      fromPlatformId: "plt_bellavista_de_la_florida_l5",
      toPlatformId: "plt_vicente_valdes_l5",
      lineId: "L5",
      direction: "INBOUND",
      sequence: 29,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
    {
      id: "seg_l5_santiago_bueras_plaza_maipu_outbound",
      fromPlatformId: "plt_santiago_bueras_l5",
      toPlatformId: "plt_plaza_de_maipu_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 1,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_del_sol_santiago_bueras_outbound",
      fromPlatformId: "plt_del_sol_l5",
      toPlatformId: "plt_santiago_bueras_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 2,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l5_monte_tabor_del_sol_outbound",
      fromPlatformId: "plt_monte_tabor_l5",
      toPlatformId: "plt_del_sol_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 3,
      distanceMeters: 1150,
      averageDurationSeconds: 105,
      timeProfiles: p(105),
    },
    {
      id: "seg_l5_las_parcelas_monte_tabor_outbound",
      fromPlatformId: "plt_las_parcelas_l5",
      toPlatformId: "plt_monte_tabor_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 4,
      distanceMeters: 1300,
      averageDurationSeconds: 112,
      timeProfiles: p(112),
    },
    {
      id: "seg_l5_laguna_sur_las_parcelas_outbound",
      fromPlatformId: "plt_laguna_sur_l5",
      toPlatformId: "plt_las_parcelas_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 5,
      distanceMeters: 3200,
      averageDurationSeconds: 200,
      timeProfiles: p(200),
    },
    {
      id: "seg_l5_barrancas_laguna_sur_outbound",
      fromPlatformId: "plt_barrancas_l5",
      toPlatformId: "plt_laguna_sur_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 6,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l5_pudahuel_barrancas_outbound",
      fromPlatformId: "plt_pudahuel_l5",
      toPlatformId: "plt_barrancas_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 7,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_san_pablo_pudahuel_outbound",
      fromPlatformId: "plt_san_pablo_l5",
      toPlatformId: "plt_pudahuel_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 8,
      distanceMeters: 1300,
      averageDurationSeconds: 112,
      timeProfiles: p(112),
    },
    {
      id: "seg_l5_lo_prado_san_pablo_outbound",
      fromPlatformId: "plt_lo_prado_l5",
      toPlatformId: "plt_san_pablo_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 9,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l5_blanqueado_lo_prado_outbound",
      fromPlatformId: "plt_blanqueado_l5",
      toPlatformId: "plt_lo_prado_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 10,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l5_gruta_blanqueado_outbound",
      fromPlatformId: "plt_gruta_de_lourdes_l5",
      toPlatformId: "plt_blanqueado_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 11,
      distanceMeters: 870,
      averageDurationSeconds: 90,
      timeProfiles: p(90),
    },
    {
      id: "seg_l5_quinta_normal_gruta_outbound",
      fromPlatformId: "plt_quinta_normal_l5",
      toPlatformId: "plt_gruta_de_lourdes_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 12,
      distanceMeters: 1600,
      averageDurationSeconds: 125,
      timeProfiles: p(125),
    },
    {
      id: "seg_l5_cumming_quinta_normal_outbound",
      fromPlatformId: "plt_cumming_l5",
      toPlatformId: "plt_quinta_normal_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 13,
      distanceMeters: 1500,
      averageDurationSeconds: 120,
      timeProfiles: p(120),
    },
    {
      id: "seg_l5_santa_ana_cumming_outbound",
      fromPlatformId: "plt_santa_ana_l5",
      toPlatformId: "plt_cumming_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 14,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_plaza_de_armas_santa_ana_outbound",
      fromPlatformId: "plt_plaza_de_armas_l5",
      toPlatformId: "plt_santa_ana_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 15,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l5_bellas_artes_plaza_de_armas_outbound",
      fromPlatformId: "plt_bellas_artes_l5",
      toPlatformId: "plt_plaza_de_armas_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 16,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l5_baquedano_bellas_artes_outbound",
      fromPlatformId: "plt_baquedano_l5",
      toPlatformId: "plt_bellas_artes_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 17,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l5_parque_bustamante_baquedano_outbound",
      fromPlatformId: "plt_parque_bustamante_l5",
      toPlatformId: "plt_baquedano_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 18,
      distanceMeters: 780,
      averageDurationSeconds: 83,
      timeProfiles: p(83),
    },
    {
      id: "seg_l5_santa_isabel_parque_bustamante_outbound",
      fromPlatformId: "plt_santa_isabel_l5",
      toPlatformId: "plt_parque_bustamante_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 19,
      distanceMeters: 820,
      averageDurationSeconds: 86,
      timeProfiles: p(86),
    },
    {
      id: "seg_l5_irarrazaval_santa_isabel_outbound",
      fromPlatformId: "plt_irarrazaval_l5",
      toPlatformId: "plt_santa_isabel_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 20,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l5_nuble_irarrazaval_outbound",
      fromPlatformId: "plt_nuble_l5",
      toPlatformId: "plt_irarrazaval_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 21,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l5_rodrigo_nuble_outbound",
      fromPlatformId: "plt_rodrigo_de_araya_l5",
      toPlatformId: "plt_nuble_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 22,
      distanceMeters: 2100,
      averageDurationSeconds: 155,
      timeProfiles: p(155),
    },
    {
      id: "seg_l5_carlos_valdovinos_rodrigo_outbound",
      fromPlatformId: "plt_carlos_valdovinos_l5",
      toPlatformId: "plt_rodrigo_de_araya_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 23,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l5_camino_agricola_carlos_valdovinos_outbound",
      fromPlatformId: "plt_camino_agricola_l5",
      toPlatformId: "plt_carlos_valdovinos_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 24,
      distanceMeters: 1000,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l5_san_joaquin_camino_agricola_outbound",
      fromPlatformId: "plt_san_joaquin_l5",
      toPlatformId: "plt_camino_agricola_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 25,
      distanceMeters: 950,
      averageDurationSeconds: 95,
      timeProfiles: p(95),
    },
    {
      id: "seg_l5_pedrero_san_joaquin_outbound",
      fromPlatformId: "plt_pedrero_l5",
      toPlatformId: "plt_san_joaquin_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 26,
      distanceMeters: 900,
      averageDurationSeconds: 92,
      timeProfiles: p(92),
    },
    {
      id: "seg_l5_mirador_pedrero_outbound",
      fromPlatformId: "plt_mirador_l5",
      toPlatformId: "plt_pedrero_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 27,
      distanceMeters: 850,
      averageDurationSeconds: 88,
      timeProfiles: p(88),
    },
    {
      id: "seg_l5_bellavista_mirador_outbound",
      fromPlatformId: "plt_bellavista_de_la_florida_l5",
      toPlatformId: "plt_mirador_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 28,
      distanceMeters: 1000,
      averageDurationSeconds: 98,
      timeProfiles: p(98),
    },
    {
      id: "seg_l5_vicente_valdes_bellavista_outbound",
      fromPlatformId: "plt_vicente_valdes_l5",
      toPlatformId: "plt_bellavista_de_la_florida_l5",
      lineId: "L5",
      direction: "OUTBOUND",
      sequence: 29,
      distanceMeters: 800,
      averageDurationSeconds: 85,
      timeProfiles: p(85),
    },
  ],
};
