import type { LineDefinition } from "../types.ts";

function p(avg: number) {
  return [
    {
      serviceId: "weekday",
      startTimeSeconds: 21600,
      endTimeSeconds: 82800,
      durationSeconds: avg,
    },
    {
      serviceId: "saturday",
      startTimeSeconds: 25200,
      endTimeSeconds: 82800,
      durationSeconds: Math.round(avg * 0.9),
    },
    {
      serviceId: "sunday_holiday",
      startTimeSeconds: 28800,
      endTimeSeconds: 75600,
      durationSeconds: Math.round(avg * 0.85),
    },
  ];
}

export const L6: LineDefinition = {
  line: { id: "L6", name: "Línea 6", color: "#8B2FC9" },
  platforms: [
    { id: "plt_cerrillos_l6", stationId: "st_cerrillos", lineId: "L6" },
    { id: "plt_lo_valledor_l6", stationId: "st_lo_valledor", lineId: "L6" },
    {
      id: "plt_presidente_pedro_aguirre_cerda_l6",
      stationId: "st_presidente_pedro_aguirre_cerda",
      lineId: "L6",
    },
    { id: "plt_franklin_l6", stationId: "st_franklin", lineId: "L6" },
    { id: "plt_bio_bio_l6", stationId: "st_bio_bio", lineId: "L6" },
    { id: "plt_nuble_l6", stationId: "st_nuble", lineId: "L6" },
    {
      id: "plt_estadio_nacional_l6",
      stationId: "st_estadio_nacional",
      lineId: "L6",
    },
    { id: "plt_nunoa_l6", stationId: "st_nunoa", lineId: "L6" },
    {
      id: "plt_ines_de_suarez_l6",
      stationId: "st_ines_de_suarez",
      lineId: "L6",
    },
    { id: "plt_los_leones_l6", stationId: "st_los_leones", lineId: "L6" },
  ],
  segments: [
    {
      id: "seg_l6_cerrillos_lo_valledor_inbound",
      fromPlatformId: "plt_cerrillos_l6",
      toPlatformId: "plt_lo_valledor_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l6_lo_valledor_presidente_inbound",
      fromPlatformId: "plt_lo_valledor_l6",
      toPlatformId: "plt_presidente_pedro_aguirre_cerda_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 2,
      distanceMeters: 1500,
      averageDurationSeconds: 120,
      timeProfiles: p(120),
    },
    {
      id: "seg_l6_presidente_franklin_inbound",
      fromPlatformId: "plt_presidente_pedro_aguirre_cerda_l6",
      toPlatformId: "plt_franklin_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 3,
      distanceMeters: 1800,
      averageDurationSeconds: 138,
      timeProfiles: p(138),
    },
    {
      id: "seg_l6_franklin_bio_bio_inbound",
      fromPlatformId: "plt_franklin_l6",
      toPlatformId: "plt_bio_bio_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 4,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l6_bio_bio_nuble_inbound",
      fromPlatformId: "plt_bio_bio_l6",
      toPlatformId: "plt_nuble_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 5,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l6_nuble_estadio_nacional_inbound",
      fromPlatformId: "plt_nuble_l6",
      toPlatformId: "plt_estadio_nacional_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 6,
      distanceMeters: 1600,
      averageDurationSeconds: 125,
      timeProfiles: p(125),
    },
    {
      id: "seg_l6_estadio_nacional_nunoa_inbound",
      fromPlatformId: "plt_estadio_nacional_l6",
      toPlatformId: "plt_nunoa_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 7,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l6_nunoa_ines_de_suarez_inbound",
      fromPlatformId: "plt_nunoa_l6",
      toPlatformId: "plt_ines_de_suarez_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 8,
      distanceMeters: 1800,
      averageDurationSeconds: 138,
      timeProfiles: p(138),
    },
    {
      id: "seg_l6_ines_de_suarez_los_leones_inbound",
      fromPlatformId: "plt_ines_de_suarez_l6",
      toPlatformId: "plt_los_leones_l6",
      lineId: "L6",
      direction: "INBOUND",
      sequence: 9,
      distanceMeters: 1600,
      averageDurationSeconds: 125,
      timeProfiles: p(125),
    },
    {
      id: "seg_l6_lo_valledor_cerrillos_outbound",
      fromPlatformId: "plt_lo_valledor_l6",
      toPlatformId: "plt_cerrillos_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 1,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l6_presidente_lo_valledor_outbound",
      fromPlatformId: "plt_presidente_pedro_aguirre_cerda_l6",
      toPlatformId: "plt_lo_valledor_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 2,
      distanceMeters: 1500,
      averageDurationSeconds: 120,
      timeProfiles: p(120),
    },
    {
      id: "seg_l6_franklin_presidente_outbound",
      fromPlatformId: "plt_franklin_l6",
      toPlatformId: "plt_presidente_pedro_aguirre_cerda_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 3,
      distanceMeters: 1800,
      averageDurationSeconds: 138,
      timeProfiles: p(138),
    },
    {
      id: "seg_l6_bio_bio_franklin_outbound",
      fromPlatformId: "plt_bio_bio_l6",
      toPlatformId: "plt_franklin_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 4,
      distanceMeters: 1200,
      averageDurationSeconds: 108,
      timeProfiles: p(108),
    },
    {
      id: "seg_l6_nuble_bio_bio_outbound",
      fromPlatformId: "plt_nuble_l6",
      toPlatformId: "plt_bio_bio_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 5,
      distanceMeters: 1400,
      averageDurationSeconds: 115,
      timeProfiles: p(115),
    },
    {
      id: "seg_l6_estadio_nacional_nuble_outbound",
      fromPlatformId: "plt_estadio_nacional_l6",
      toPlatformId: "plt_nuble_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 6,
      distanceMeters: 1600,
      averageDurationSeconds: 125,
      timeProfiles: p(125),
    },
    {
      id: "seg_l6_nunoa_estadio_nacional_outbound",
      fromPlatformId: "plt_nunoa_l6",
      toPlatformId: "plt_estadio_nacional_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 7,
      distanceMeters: 1100,
      averageDurationSeconds: 103,
      timeProfiles: p(103),
    },
    {
      id: "seg_l6_ines_de_suarez_nunoa_outbound",
      fromPlatformId: "plt_ines_de_suarez_l6",
      toPlatformId: "plt_nunoa_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 8,
      distanceMeters: 1800,
      averageDurationSeconds: 138,
      timeProfiles: p(138),
    },
    {
      id: "seg_l6_los_leones_ines_de_suarez_outbound",
      fromPlatformId: "plt_los_leones_l6",
      toPlatformId: "plt_ines_de_suarez_l6",
      lineId: "L6",
      direction: "OUTBOUND",
      sequence: 9,
      distanceMeters: 1600,
      averageDurationSeconds: 125,
      timeProfiles: p(125),
    },
  ],
};
