import type { StationSeed } from "./types.ts";

export const STATIONS: StationSeed[] = [
  {
    id: "st_san_pablo",
    name: "San Pablo",
    shortCode: "SPB",
    latitude: -33.4458,
    longitude: -70.7223,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_neptuno",
    name: "Neptuno",
    shortCode: "NEP",
    latitude: -33.4478,
    longitude: -70.7138,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pajaritos",
    name: "Pajaritos",
    shortCode: "PAJ",
    latitude: -33.4496,
    longitude: -70.698,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_las_rejas",
    name: "Las Rejas",
    shortCode: "LRJ",
    latitude: -33.4529,
    longitude: -70.6864,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_ecuador",
    name: "Ecuador",
    shortCode: "ECU",
    latitude: -33.4556,
    longitude: -70.6742,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_alberto_hurtado",
    name: "San Alberto Hurtado",
    shortCode: "SAH",
    latitude: -33.4583,
    longitude: -70.6636,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_universidad_de_santiago",
    name: "Universidad de Santiago",
    shortCode: "UDS",
    latitude: -33.4589,
    longitude: -70.6572,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_estacion_central",
    name: "Estación Central",
    shortCode: "ECN",
    latitude: -33.4565,
    longitude: -70.6807,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_union_latinoamericana",
    name: "Unión Latinoamericana",
    shortCode: "ULA",
    latitude: -33.4552,
    longitude: -70.6518,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_republica",
    name: "República",
    shortCode: "REP",
    latitude: -33.4549,
    longitude: -70.6441,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_heroes",
    name: "Los Héroes",
    shortCode: "LHR",
    latitude: -33.4513,
    longitude: -70.6624,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_la_moneda",
    name: "La Moneda",
    shortCode: "LMN",
    latitude: -33.4408,
    longitude: -70.6535,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_universidad_de_chile",
    name: "Universidad de Chile",
    shortCode: "UCH",
    latitude: -33.4431,
    longitude: -70.6506,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_santa_lucia",
    name: "Santa Lucía",
    shortCode: "SLU",
    latitude: -33.4418,
    longitude: -70.6435,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_universidad_catolica",
    name: "Universidad Católica",
    shortCode: "UCA",
    latitude: -33.4406,
    longitude: -70.6407,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_baquedano",
    name: "Baquedano",
    shortCode: "BAQ",
    latitude: -33.4385,
    longitude: -70.6374,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_salvador",
    name: "Salvador",
    shortCode: "SAL",
    latitude: -33.4372,
    longitude: -70.6276,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_manuel_montt",
    name: "Manuel Montt",
    shortCode: "MMT",
    latitude: -33.4358,
    longitude: -70.6192,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pedro_de_valdivia",
    name: "Pedro de Valdivia",
    shortCode: "PDV",
    latitude: -33.4337,
    longitude: -70.6134,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_leones",
    name: "Los Leones",
    shortCode: "LLN",
    latitude: -33.432,
    longitude: -70.6168,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_tobalaba",
    name: "Tobalaba",
    shortCode: "TOB",
    latitude: -33.432,
    longitude: -70.6072,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_el_golf",
    name: "El Golf",
    shortCode: "ELG",
    latitude: -33.4145,
    longitude: -70.5974,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_alcantara",
    name: "Alcántara",
    shortCode: "ALC",
    latitude: -33.4082,
    longitude: -70.5889,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_escuela_militar",
    name: "Escuela Militar",
    shortCode: "ESM",
    latitude: -33.3985,
    longitude: -70.5788,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_manquehue",
    name: "Manquehue",
    shortCode: "MNQ",
    latitude: -33.3952,
    longitude: -70.5736,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_hernando_de_magallanes",
    name: "Hernando de Magallanes",
    shortCode: "HDM",
    latitude: -33.3936,
    longitude: -70.5721,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_dominicos",
    name: "Los Dominicos",
    shortCode: "LDM",
    latitude: -33.3978,
    longitude: -70.5698,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_la_cisterna",
    name: "La Cisterna",
    shortCode: "LCS",
    latitude: -33.5316,
    longitude: -70.6593,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_el_parron",
    name: "El Parrón",
    shortCode: "EPR",
    latitude: -33.5194,
    longitude: -70.6582,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_ovalle",
    name: "Lo Ovalle",
    shortCode: "LOV",
    latitude: -33.5098,
    longitude: -70.6574,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_ciudad_del_nino",
    name: "Ciudad del Niño",
    shortCode: "CDN",
    latitude: -33.5024,
    longitude: -70.6568,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_departamental",
    name: "Departamental",
    shortCode: "DEP",
    latitude: -33.4956,
    longitude: -70.6562,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_vial",
    name: "Lo Vial",
    shortCode: "LVI",
    latitude: -33.4882,
    longitude: -70.6557,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_miguel",
    name: "San Miguel",
    shortCode: "SMG",
    latitude: -33.4991,
    longitude: -70.6551,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_el_llano",
    name: "El Llano",
    shortCode: "ELL",
    latitude: -33.4927,
    longitude: -70.6548,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_franklin",
    name: "Franklin",
    shortCode: "FRK",
    latitude: -33.4902,
    longitude: -70.6548,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_rondizzoni",
    name: "Rondizzoni",
    shortCode: "RON",
    latitude: -33.4846,
    longitude: -70.6544,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_parque_ohiggins",
    name: "Parque O'Higgins",
    shortCode: "POH",
    latitude: -33.4774,
    longitude: -70.6572,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_toesca",
    name: "Toesca",
    shortCode: "TOE",
    latitude: -33.4689,
    longitude: -70.6579,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_santa_ana",
    name: "Santa Ana",
    shortCode: "SAN",
    latitude: -33.4386,
    longitude: -70.6584,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_puente_cal_y_canto",
    name: "Puente Cal y Canto",
    shortCode: "PCC",
    latitude: -33.4305,
    longitude: -70.6533,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_patronato",
    name: "Patronato",
    shortCode: "PAT",
    latitude: -33.4248,
    longitude: -70.6492,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cerro_blanco",
    name: "Cerro Blanco",
    shortCode: "CBL",
    latitude: -33.4162,
    longitude: -70.6458,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cementerios",
    name: "Cementerios",
    shortCode: "CEM",
    latitude: -33.4078,
    longitude: -70.6442,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_einstein",
    name: "Einstein",
    shortCode: "EIN",
    latitude: -33.4004,
    longitude: -70.6436,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_dorsal",
    name: "Dorsal",
    shortCode: "DOR",
    latitude: -33.3938,
    longitude: -70.6431,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_zapadores",
    name: "Zapadores",
    shortCode: "ZAP",
    latitude: -33.3872,
    longitude: -70.6427,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_vespucio_norte",
    name: "Vespucio Norte",
    shortCode: "VPN",
    latitude: -33.3812,
    longitude: -70.6432,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_libertadores",
    name: "Los Libertadores",
    shortCode: "LLB",
    latitude: -33.3936,
    longitude: -70.6482,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cardenal_caro",
    name: "Cardenal Caro",
    shortCode: "CAR",
    latitude: -33.3998,
    longitude: -70.6476,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_vivaceta",
    name: "Vivaceta",
    shortCode: "VIV",
    latitude: -33.4064,
    longitude: -70.6471,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_conchali",
    name: "Conchalí",
    shortCode: "CON",
    latitude: -33.4132,
    longitude: -70.6465,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_chacabuco",
    name: "Plaza Chacabuco",
    shortCode: "PCH",
    latitude: -33.4198,
    longitude: -70.646,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_hospitales",
    name: "Hospitales",
    shortCode: "HOS",
    latitude: -33.4264,
    longitude: -70.6512,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_de_armas",
    name: "Plaza de Armas",
    shortCode: "PDA",
    latitude: -33.4371,
    longitude: -70.652,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_parque_almagro",
    name: "Parque Almagro",
    shortCode: "PAL",
    latitude: -33.4478,
    longitude: -70.6462,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_matta",
    name: "Matta",
    shortCode: "MAT",
    latitude: -33.4524,
    longitude: -70.6398,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_irarrazaval",
    name: "Irarrázaval",
    shortCode: "IRA",
    latitude: -33.4574,
    longitude: -70.6219,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_monsenor_eyzaguirre",
    name: "Monseñor Eyzaguirre",
    shortCode: "MEY",
    latitude: -33.4568,
    longitude: -70.6132,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_nunoa",
    name: "Ñuñoa",
    shortCode: "NUN",
    latitude: -33.4568,
    longitude: -70.599,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_chile_espana",
    name: "Chile-España",
    shortCode: "CES",
    latitude: -33.4552,
    longitude: -70.5938,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_villa_frei",
    name: "Villa Frei",
    shortCode: "VFR",
    latitude: -33.4538,
    longitude: -70.5882,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_egana",
    name: "Plaza Egaña",
    shortCode: "PEG",
    latitude: -33.4522,
    longitude: -70.5834,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_fernando_castillo_velasco",
    name: "Fernando Castillo Velasco",
    shortCode: "FCV",
    latitude: -33.4516,
    longitude: -70.5786,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cristobal_colon",
    name: "Cristóbal Colón",
    shortCode: "CCO",
    latitude: -33.4256,
    longitude: -70.6078,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_francisco_bilbao",
    name: "Francisco Bilbao",
    shortCode: "FBL",
    latitude: -33.4212,
    longitude: -70.6052,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_principe_de_gales",
    name: "Príncipe de Gales",
    shortCode: "PDG",
    latitude: -33.4328,
    longitude: -70.6014,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_simon_bolivar",
    name: "Simón Bolívar",
    shortCode: "SBO",
    latitude: -33.4402,
    longitude: -70.5976,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_orientales",
    name: "Los Orientales",
    shortCode: "LOR",
    latitude: -33.4478,
    longitude: -70.5938,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_grecia",
    name: "Grecia",
    shortCode: "GRE",
    latitude: -33.4524,
    longitude: -70.5892,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_presidentes",
    name: "Los Presidentes",
    shortCode: "LPR",
    latitude: -33.4588,
    longitude: -70.5846,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_quilin",
    name: "Quilín",
    shortCode: "QUI",
    latitude: -33.4632,
    longitude: -70.5802,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_las_torres",
    name: "Las Torres",
    shortCode: "LTO",
    latitude: -33.4684,
    longitude: -70.5774,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_macul",
    name: "Macul",
    shortCode: "MAC",
    latitude: -33.4746,
    longitude: -70.5742,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_vicuna_mackenna",
    name: "Vicuña Mackenna",
    shortCode: "VMK",
    latitude: -33.4918,
    longitude: -70.6018,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_vicente_valdes",
    name: "Vicente Valdés",
    shortCode: "VVA",
    latitude: -33.5362,
    longitude: -70.601,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_rojas_magallanes",
    name: "Rojas Magallanes",
    shortCode: "RMG",
    latitude: -33.5394,
    longitude: -70.5948,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_trinidad",
    name: "Trinidad",
    shortCode: "TRI",
    latitude: -33.5442,
    longitude: -70.5884,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_jose_de_la_estrella",
    name: "San José de la Estrella",
    shortCode: "SJE",
    latitude: -33.5498,
    longitude: -70.5812,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_quillayes",
    name: "Los Quillayes",
    shortCode: "LQL",
    latitude: -33.5542,
    longitude: -70.5754,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_elisa_correa",
    name: "Elisa Correa",
    shortCode: "ELC",
    latitude: -33.5588,
    longitude: -70.5706,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_hospital_sotero_del_rio",
    name: "Hospital Sótero del Río",
    shortCode: "HSR",
    latitude: -33.5634,
    longitude: -70.5668,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_protectora_de_la_infancia",
    name: "Protectora de la Infancia",
    shortCode: "PDI",
    latitude: -33.5672,
    longitude: -70.5622,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_las_mercedes",
    name: "Las Mercedes",
    shortCode: "LME",
    latitude: -33.5708,
    longitude: -70.5584,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_de_puente_alto",
    name: "Plaza de Puente Alto",
    shortCode: "PPA",
    latitude: -33.5742,
    longitude: -70.5774,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_santa_julia",
    name: "Santa Julia",
    shortCode: "SJU",
    latitude: -33.5002,
    longitude: -70.6044,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_la_granja",
    name: "La Granja",
    shortCode: "LGR",
    latitude: -33.5106,
    longitude: -70.6072,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_santa_rosa",
    name: "Santa Rosa",
    shortCode: "SRO",
    latitude: -33.5198,
    longitude: -70.6174,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_ramon",
    name: "San Ramón",
    shortCode: "SRM",
    latitude: -33.5264,
    longitude: -70.6312,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_de_maipu",
    name: "Plaza de Maipú",
    shortCode: "PDM",
    latitude: -33.5126,
    longitude: -70.7672,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_santiago_bueras",
    name: "Santiago Bueras",
    shortCode: "SBU",
    latitude: -33.5074,
    longitude: -70.7544,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_del_sol",
    name: "Del Sol",
    shortCode: "DSL",
    latitude: -33.5018,
    longitude: -70.7428,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_monte_tabor",
    name: "Monte Tabor",
    shortCode: "MNT",
    latitude: -33.4956,
    longitude: -70.7312,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_las_parcelas",
    name: "Las Parcelas",
    shortCode: "LPC",
    latitude: -33.4892,
    longitude: -70.7198,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_laguna_sur",
    name: "Laguna Sur",
    shortCode: "LSU",
    latitude: -33.4798,
    longitude: -70.7564,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_barrancas",
    name: "Barrancas",
    shortCode: "BAR",
    latitude: -33.4674,
    longitude: -70.7642,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pudahuel",
    name: "Pudahuel",
    shortCode: "PDH",
    latitude: -33.4477,
    longitude: -70.7575,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_prado",
    name: "Lo Prado",
    shortCode: "LPD",
    latitude: -33.4472,
    longitude: -70.7428,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_blanqueado",
    name: "Blanqueado",
    shortCode: "BLQ",
    latitude: -33.4468,
    longitude: -70.7336,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_gruta_de_lourdes",
    name: "Gruta de Lourdes",
    shortCode: "GDL",
    latitude: -33.4464,
    longitude: -70.7238,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_quinta_normal",
    name: "Quinta Normal",
    shortCode: "QNO",
    latitude: -33.4368,
    longitude: -70.7014,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cumming",
    name: "Cumming",
    shortCode: "CUM",
    latitude: -33.4382,
    longitude: -70.6846,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_bellas_artes",
    name: "Bellas Artes",
    shortCode: "BLA",
    latitude: -33.438,
    longitude: -70.6484,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_parque_bustamante",
    name: "Parque Bustamante",
    shortCode: "PBU",
    latitude: -33.4396,
    longitude: -70.6328,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_santa_isabel",
    name: "Santa Isabel",
    shortCode: "SIS",
    latitude: -33.4474,
    longitude: -70.6264,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_nuble",
    name: "Ñuble",
    shortCode: "NBL",
    latitude: -33.4558,
    longitude: -70.6262,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_rodrigo_de_araya",
    name: "Rodrigo de Araya",
    shortCode: "RDA",
    latitude: -33.4794,
    longitude: -70.6168,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_carlos_valdovinos",
    name: "Carlos Valdovinos",
    shortCode: "CVA",
    latitude: -33.4912,
    longitude: -70.6124,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_camino_agricola",
    name: "Camino Agrícola",
    shortCode: "CAG",
    latitude: -33.4988,
    longitude: -70.6082,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_joaquin",
    name: "San Joaquín",
    shortCode: "SJQ",
    latitude: -33.5062,
    longitude: -70.6048,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pedrero",
    name: "Pedrero",
    shortCode: "PED",
    latitude: -33.5128,
    longitude: -70.6022,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_mirador",
    name: "Mirador",
    shortCode: "MIR",
    latitude: -33.5194,
    longitude: -70.5998,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_bellavista_de_la_florida",
    name: "Bellavista de La Florida",
    shortCode: "BLF",
    latitude: -33.5278,
    longitude: -70.5764,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cerrillos",
    name: "Cerrillos",
    shortCode: "CER",
    latitude: -33.4928,
    longitude: -70.7244,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_valledor",
    name: "Lo Valledor",
    shortCode: "LVL",
    latitude: -33.4944,
    longitude: -70.7162,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_presidente_pedro_aguirre_cerda",
    name: "Presidente Pedro Aguirre Cerda",
    shortCode: "PAC",
    latitude: -33.4942,
    longitude: -70.6986,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_bio_bio",
    name: "Bío Bío",
    shortCode: "BIO",
    latitude: -33.4804,
    longitude: -70.6622,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_estadio_nacional",
    name: "Estadio Nacional",
    shortCode: "EST",
    latitude: -33.456,
    longitude: -70.6135,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_ines_de_suarez",
    name: "Inés de Suárez",
    shortCode: "IDS",
    latitude: -33.4358,
    longitude: -70.6022,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
];
