import type { StationSeed } from "./types.ts";

export const STATIONS: StationSeed[] = [
  {
    id: "st_san_pablo",
    name: "San Pablo",
    shortCode: "SPB",
    latitude: -33.44486,
    longitude: -70.72301999999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_neptuno",
    name: "Neptuno",
    shortCode: "NEP",
    latitude: -33.451546,
    longitude: -70.722687,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pajaritos",
    name: "Pajaritos",
    shortCode: "PAJ",
    latitude: -33.4574192,
    longitude: -70.71592570000001,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_las_rejas",
    name: "Las Rejas",
    shortCode: "LRJ",
    latitude: -33.4574571,
    longitude: -70.7063254,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_ecuador",
    name: "Ecuador",
    shortCode: "ECU",
    latitude: -33.45605,
    longitude: -70.69967,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_alberto_hurtado",
    name: "San Alberto Hurtado",
    shortCode: "SAH",
    latitude: -33.454143,
    longitude: -70.69229260000002,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_universidad_de_santiago",
    name: "Universidad de Santiago",
    shortCode: "UDS",
    latitude: -33.45290000000001,
    longitude: -70.68615,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_estacion_central",
    name: "Estación Central",
    shortCode: "ECN",
    latitude: -33.4513816,
    longitude: -70.67906289999999,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_union_latinoamericana",
    name: "Unión Latinoamericana",
    shortCode: "ULA",
    latitude: -33.44947,
    longitude: -70.6732,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_republica",
    name: "República",
    shortCode: "REP",
    latitude: -33.4477218,
    longitude: -70.6670293,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_heroes",
    name: "Los Héroes",
    shortCode: "LHR",
    latitude: -33.44615,
    longitude: -70.66038,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_la_moneda",
    name: "La Moneda",
    shortCode: "LMN",
    latitude: -33.44486,
    longitude: -70.65481,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_universidad_de_chile",
    name: "Universidad de Chile",
    shortCode: "UCH",
    latitude: -33.443809,
    longitude: -70.650391,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_santa_lucia",
    name: "Santa Lucía",
    shortCode: "SLU",
    latitude: -33.44269,
    longitude: -70.64572000000001,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_universidad_catolica",
    name: "Universidad Católica",
    shortCode: "UCA",
    latitude: -33.44022,
    longitude: -70.64054999999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_baquedano",
    name: "Baquedano",
    shortCode: "BAQ",
    latitude: -33.43746,
    longitude: -70.63416,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_salvador",
    name: "Salvador",
    shortCode: "SAL",
    latitude: -33.43311,
    longitude: -70.62659,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_manuel_montt",
    name: "Manuel Montt",
    shortCode: "MMT",
    latitude: -33.42834,
    longitude: -70.61921,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pedro_de_valdivia",
    name: "Pedro de Valdivia",
    shortCode: "PDV",
    latitude: -33.42547,
    longitude: -70.61426999999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_leones",
    name: "Los Leones",
    shortCode: "LLN",
    latitude: -33.4221279,
    longitude: -70.60845739999999,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_tobalaba",
    name: "Tobalaba",
    shortCode: "TOB",
    latitude: -33.4857085,
    longitude: -70.5584371,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_el_golf",
    name: "El Golf",
    shortCode: "ELG",
    latitude: -33.41671669999999,
    longitude: -70.5961019,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_alcantara",
    name: "Alcántara",
    shortCode: "ALC",
    latitude: -33.4153491,
    longitude: -70.58941999999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_escuela_militar",
    name: "Escuela Militar",
    shortCode: "ESM",
    latitude: -33.413517,
    longitude: -70.5832512,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_manquehue",
    name: "Manquehue",
    shortCode: "MNQ",
    latitude: -33.409034,
    longitude: -70.5686154,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_hernando_de_magallanes",
    name: "Hernando de Magallanes",
    shortCode: "HDM",
    latitude: -33.408265,
    longitude: -70.55616239999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_dominicos",
    name: "Los Dominicos",
    shortCode: "LDM",
    latitude: -33.4079,
    longitude: -70.54511,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_la_cisterna",
    name: "La Cisterna",
    shortCode: "LCS",
    latitude: -33.5373549,
    longitude: -70.6643055,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_el_parron",
    name: "El Parrón",
    shortCode: "EPR",
    latitude: -33.5264173,
    longitude: -70.6610065,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_ovalle",
    name: "Lo Ovalle",
    shortCode: "LOV",
    latitude: -33.5172,
    longitude: -70.65871,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_ciudad_del_nino",
    name: "Ciudad del Niño",
    shortCode: "CDN",
    latitude: -33.5097547,
    longitude: -70.656716,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_departamental",
    name: "Departamental",
    shortCode: "DEP",
    latitude: -33.5024916,
    longitude: -70.65464,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_vial",
    name: "Lo Vial",
    shortCode: "LVI",
    latitude: -33.49727,
    longitude: -70.65311,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_miguel",
    name: "San Miguel",
    shortCode: "SMG",
    latitude: -33.4888,
    longitude: -70.65118000000001,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_el_llano",
    name: "El Llano",
    shortCode: "ELL",
    latitude: -33.482703,
    longitude: -70.6492315,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_franklin",
    name: "Franklin",
    shortCode: "FRK",
    latitude: -33.4763781,
    longitude: -70.6492337,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_rondizzoni",
    name: "Rondizzoni",
    shortCode: "RON",
    latitude: -33.47004,
    longitude: -70.65633,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_parque_ohiggins",
    name: "Parque O'Higgins",
    shortCode: "POH",
    latitude: -33.4609788,
    longitude: -70.6568466,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_toesca",
    name: "Toesca",
    shortCode: "TOE",
    latitude: -33.4529468,
    longitude: -70.65855,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_santa_ana",
    name: "Santa Ana",
    shortCode: "SAN",
    latitude: -33.43810330000001,
    longitude: -70.6599026,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_puente_cal_y_canto",
    name: "Puente Cal y Canto",
    shortCode: "PCC",
    latitude: -33.4327343,
    longitude: -70.6523831,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_patronato",
    name: "Patronato",
    shortCode: "PAT",
    latitude: -33.42963,
    longitude: -70.64706,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cerro_blanco",
    name: "Cerro Blanco",
    shortCode: "CBL",
    latitude: -33.42255,
    longitude: -70.64497,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cementerios",
    name: "Cementerios",
    shortCode: "CEM",
    latitude: -33.4139575,
    longitude: -70.6437062,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_einstein",
    name: "Einstein",
    shortCode: "EIN",
    latitude: -33.40573,
    longitude: -70.64314,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_dorsal",
    name: "Dorsal",
    shortCode: "DOR",
    latitude: -33.3967662,
    longitude: -70.643089,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_zapadores",
    name: "Zapadores",
    shortCode: "ZAP",
    latitude: -33.3911584,
    longitude: -70.6424719,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_vespucio_norte",
    name: "Vespucio Norte",
    shortCode: "VPN",
    latitude: -33.38043,
    longitude: -70.64681999999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_libertadores",
    name: "Los Libertadores",
    shortCode: "LLB",
    latitude: -33.365353,
    longitude: -70.69187870000002,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cardenal_caro",
    name: "Cardenal Caro",
    shortCode: "CAR",
    latitude: -33.3732813,
    longitude: -70.68624369999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_vivaceta",
    name: "Vivaceta",
    shortCode: "VIV",
    latitude: -33.38587700000001,
    longitude: -70.679226,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_conchali",
    name: "Conchalí",
    shortCode: "CON",
    latitude: -33.3974145,
    longitude: -70.6695711,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_chacabuco",
    name: "Plaza Chacabuco",
    shortCode: "PCH",
    latitude: -33.40644,
    longitude: -70.66087,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_hospitales",
    name: "Hospitales",
    shortCode: "HOS",
    latitude: -33.417663,
    longitude: -70.656373,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_de_armas",
    name: "Plaza de Armas",
    shortCode: "PDA",
    latitude: -33.4370952,
    longitude: -70.6511867,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_parque_almagro",
    name: "Parque Almagro",
    shortCode: "PAL",
    latitude: -33.451498,
    longitude: -70.6506302,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_matta",
    name: "Matta",
    shortCode: "MAT",
    latitude: -33.4579416,
    longitude: -70.6431218,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_irarrazaval",
    name: "Irarrázaval",
    shortCode: "IRA",
    latitude: -33.453135,
    longitude: -70.62892939999999,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_monsenor_eyzaguirre",
    name: "Monseñor Eyzaguirre",
    shortCode: "MEY",
    latitude: -33.453164,
    longitude: -70.613835,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_nunoa",
    name: "Ñuñoa",
    shortCode: "NUN",
    latitude: -33.4544707,
    longitude: -70.605443,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_chile_espana",
    name: "Chile-España",
    shortCode: "CES",
    latitude: -33.45495,
    longitude: -70.59747999999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_villa_frei",
    name: "Villa Frei",
    shortCode: "VFR",
    latitude: -33.4548127,
    longitude: -70.5801523,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_egana",
    name: "Plaza Egaña",
    shortCode: "PEG",
    latitude: -33.45328,
    longitude: -70.57073,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_fernando_castillo_velasco",
    name: "Fernando Castillo Velasco",
    shortCode: "FCV",
    latitude: -33.45232,
    longitude: -70.55818,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cristobal_colon",
    name: "Cristóbal Colón",
    shortCode: "CCO",
    latitude: -33.4262968,
    longitude: -70.59125,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_francisco_bilbao",
    name: "Francisco Bilbao",
    shortCode: "FBL",
    latitude: -33.43134670000001,
    longitude: -70.58495549999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_principe_de_gales",
    name: "Príncipe de Gales",
    shortCode: "PDG",
    latitude: -33.43916,
    longitude: -70.57309,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_simon_bolivar",
    name: "Simón Bolívar",
    shortCode: "SBO",
    latitude: -33.4463745,
    longitude: -70.57205569999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_orientales",
    name: "Los Orientales",
    shortCode: "LOR",
    latitude: -33.4621758,
    longitude: -70.5741443,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_grecia",
    name: "Grecia",
    shortCode: "GRE",
    latitude: -33.468819,
    longitude: -70.576202,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_presidentes",
    name: "Los Presidentes",
    shortCode: "LPR",
    latitude: -33.4798,
    longitude: -70.57871,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_quilin",
    name: "Quilín",
    shortCode: "QUI",
    latitude: -33.4883713,
    longitude: -70.5804364,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_las_torres",
    name: "Las Torres",
    shortCode: "LTO",
    latitude: -33.4991663,
    longitude: -70.5865711,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_macul",
    name: "Macul",
    shortCode: "MAC",
    latitude: -33.5089465,
    longitude: -70.5900424,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_vicuna_mackenna",
    name: "Vicuña Mackenna",
    shortCode: "VMK",
    latitude: -33.519642,
    longitude: -70.596069,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_vicente_valdes",
    name: "Vicente Valdés",
    shortCode: "VVA",
    latitude: -33.526337,
    longitude: -70.596756,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_rojas_magallanes",
    name: "Rojas Magallanes",
    shortCode: "RMG",
    latitude: -33.53624,
    longitude: -70.5926142,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_trinidad",
    name: "Trinidad",
    shortCode: "TRI",
    latitude: -33.5461158,
    longitude: -70.58820759999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_jose_de_la_estrella",
    name: "San José de la Estrella",
    shortCode: "SJE",
    latitude: -33.5536409,
    longitude: -70.5865972,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_los_quillayes",
    name: "Los Quillayes",
    shortCode: "LQL",
    latitude: -33.5612052,
    longitude: -70.585253,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_elisa_correa",
    name: "Elisa Correa",
    shortCode: "ELC",
    latitude: -33.5693531,
    longitude: -70.58379699999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_hospital_sotero_del_rio",
    name: "Hospital Sótero del Río",
    shortCode: "HSR",
    latitude: -33.5768784,
    longitude: -70.5822951,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_protectora_de_la_infancia",
    name: "Protectora de la Infancia",
    shortCode: "PDI",
    latitude: -33.5895734,
    longitude: -70.5798394,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_las_mercedes",
    name: "Las Mercedes",
    shortCode: "LME",
    latitude: -33.6014017,
    longitude: -70.57746279999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_de_puente_alto",
    name: "Plaza de Puente Alto",
    shortCode: "PPA",
    latitude: -33.60955,
    longitude: -70.57591,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_santa_julia",
    name: "Santa Julia",
    shortCode: "SJU",
    latitude: -33.5311,
    longitude: -70.60553999999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_la_granja",
    name: "La Granja",
    shortCode: "LGR",
    latitude: -33.54115000000001,
    longitude: -70.61604,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_santa_rosa",
    name: "Santa Rosa",
    shortCode: "SRO",
    latitude: -33.5424171,
    longitude: -70.63415180000001,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_ramon",
    name: "San Ramón",
    shortCode: "SRM",
    latitude: -33.5412191,
    longitude: -70.643224,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_plaza_de_maipu",
    name: "Plaza de Maipú",
    shortCode: "PDM",
    latitude: -33.51052,
    longitude: -70.75722999999999,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_santiago_bueras",
    name: "Santiago Bueras",
    shortCode: "SBU",
    latitude: -33.4968828,
    longitude: -70.757054,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_del_sol",
    name: "Del Sol",
    shortCode: "DSL",
    latitude: -33.490116,
    longitude: -70.753063,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_monte_tabor",
    name: "Monte Tabor",
    shortCode: "MNT",
    latitude: -33.4822141,
    longitude: -70.7453951,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_las_parcelas",
    name: "Las Parcelas",
    shortCode: "LPC",
    latitude: -33.475394,
    longitude: -70.740043,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_laguna_sur",
    name: "Laguna Sur",
    shortCode: "LSU",
    latitude: -33.4621238,
    longitude: -70.73791779999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_barrancas",
    name: "Barrancas",
    shortCode: "BAR",
    latitude: -33.452669,
    longitude: -70.73901699999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pudahuel",
    name: "Pudahuel",
    shortCode: "PDH",
    latitude: -33.4449541,
    longitude: -70.7409325,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_prado",
    name: "Lo Prado",
    shortCode: "LPD",
    latitude: -33.4433,
    longitude: -70.71641,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_blanqueado",
    name: "Blanqueado",
    shortCode: "BLQ",
    latitude: -33.4410801,
    longitude: -70.7068291,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_gruta_de_lourdes",
    name: "Gruta de Lourdes",
    shortCode: "GDL",
    latitude: -33.43826,
    longitude: -70.69084,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_quinta_normal",
    name: "Quinta Normal",
    shortCode: "QNO",
    latitude: -33.4405051,
    longitude: -70.68007260000002,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cumming",
    name: "Cumming",
    shortCode: "CUM",
    latitude: -33.4391,
    longitude: -70.66843,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_bellas_artes",
    name: "Bellas Artes",
    shortCode: "BLA",
    latitude: -33.4364506,
    longitude: -70.64422139999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_parque_bustamante",
    name: "Parque Bustamante",
    shortCode: "PBU",
    latitude: -33.4428392,
    longitude: -70.63163399999999,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_santa_isabel",
    name: "Santa Isabel",
    shortCode: "SIS",
    latitude: -33.4470595,
    longitude: -70.630651,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_nuble",
    name: "Ñuble",
    shortCode: "NBL",
    latitude: -33.46719,
    longitude: -70.62519,
    isUnderground: true,
    hasElevator: true,
    hasEscalator: true,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_rodrigo_de_araya",
    name: "Rodrigo de Araya",
    shortCode: "RDA",
    latitude: -33.477516,
    longitude: -70.622314,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_carlos_valdovinos",
    name: "Carlos Valdovinos",
    shortCode: "CVA",
    latitude: -33.4864172,
    longitude: -70.61917559999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_camino_agricola",
    name: "Camino Agrícola",
    shortCode: "CAG",
    latitude: -33.4917505,
    longitude: -70.61753089999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_san_joaquin",
    name: "San Joaquín",
    shortCode: "SJQ",
    latitude: -33.4992462,
    longitude: -70.6158507,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_pedrero",
    name: "Pedrero",
    shortCode: "PED",
    latitude: -33.507812,
    longitude: -70.61266300000001,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_mirador",
    name: "Mirador",
    shortCode: "MIR",
    latitude: -33.5132631,
    longitude: -70.6060067,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_bellavista_de_la_florida",
    name: "Bellavista de La Florida",
    shortCode: "BLF",
    latitude: -33.5198266,
    longitude: -70.59965799999999,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_cerrillos",
    name: "Cerrillos",
    shortCode: "CER",
    latitude: -33.4834157,
    longitude: -70.6955534,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_lo_valledor",
    name: "Lo Valledor",
    shortCode: "LVL",
    latitude: -33.4773007,
    longitude: -70.6806502,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_presidente_pedro_aguirre_cerda",
    name: "Pedro Aguirre Cerda",
    shortCode: "PAC",
    latitude: -33.478681,
    longitude: -70.664706,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_bio_bio",
    name: "Bío Bío",
    shortCode: "BIO",
    latitude: -33.4767954,
    longitude: -70.6423473,
    isUnderground: false,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_estadio_nacional",
    name: "Estadio Nacional",
    shortCode: "EST",
    latitude: -33.462282,
    longitude: -70.606113,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  {
    id: "st_ines_de_suarez",
    name: "Inés de Suárez",
    shortCode: "IDS",
    latitude: -33.438878,
    longitude: -70.60720100000002,
    isUnderground: true,
    hasElevator: false,
    hasEscalator: false,
    wheelchairAccessible: false,
    entrances: [],
  },
  // ── Extensão Sul L2 (2023) ──────────────────────────────────────────────────
  {
    id: "st_el_bosque",
    name: "El Bosque",
    shortCode: "EBS",
    latitude: -33.54652,
    longitude: -70.66668,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_observatorio",
    name: "Observatorio",
    shortCode: "OBS",
    latitude: -33.56037,
    longitude: -70.67048,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_copa_lo_martinez",
    name: "Copa Lo Martínez",
    shortCode: "CLM",
    latitude: -33.57089,
    longitude: -70.67342,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_hospital_el_pino",
    name: "Hospital El Pino",
    shortCode: "HEP",
    latitude: -33.58295,
    longitude: -70.67678,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  // ── Extensão Noroeste L3 (2023) ──────────────────────────────────────────────
  {
    id: "st_ferrocarril",
    name: "Ferrocarril",
    shortCode: "FCR",
    latitude: -33.36557,
    longitude: -70.70573999999999,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_lo_cruzat",
    name: "Lo Cruzat",
    shortCode: "LCZ",
    latitude: -33.36645,
    longitude: -70.72187,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
  {
    id: "st_plaza_quilicura",
    name: "Plaza Quilicura",
    shortCode: "PQL",
    latitude: -33.3660915,
    longitude: -70.7300094,
    isUnderground: false,
    hasElevator: true,
    hasEscalator: false,
    wheelchairAccessible: true,
    entrances: [],
  },
];
