import type { TransferSeed } from "./types.ts";

export const TRANSFERS: TransferSeed[] = [
  {
    id: "itf_san_pablo_l1_l5",
    fromPlatformId: "plt_san_pablo_l1",
    toPlatformId: "plt_san_pablo_l5",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_los_heroes_l1_l2",
    fromPlatformId: "plt_los_heroes_l1",
    toPlatformId: "plt_los_heroes_l2",
    walkingSeconds: 180,
    accessibilityFriendly: true,
    platformChange: true,
  },
  {
    id: "itf_uch_l1_l3",
    fromPlatformId: "plt_universidad_de_chile_l1",
    toPlatformId: "plt_universidad_de_chile_l3",
    walkingSeconds: 180,
    accessibilityFriendly: true,
    platformChange: true,
  },
  {
    id: "itf_baquedano_l1_l5",
    fromPlatformId: "plt_baquedano_l1",
    toPlatformId: "plt_baquedano_l5",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_los_leones_l1_l6",
    fromPlatformId: "plt_los_leones_l1",
    toPlatformId: "plt_los_leones_l6",
    walkingSeconds: 300,
    accessibilityFriendly: false,
    platformChange: true,
  },
  {
    id: "itf_tobalaba_l1_l4",
    fromPlatformId: "plt_tobalaba_l1",
    toPlatformId: "plt_tobalaba_l4",
    walkingSeconds: 180,
    accessibilityFriendly: true,
    platformChange: true,
  },
  {
    id: "itf_la_cisterna_l2_l4a",
    fromPlatformId: "plt_la_cisterna_l2",
    toPlatformId: "plt_la_cisterna_l4a",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_franklin_l2_l6",
    fromPlatformId: "plt_franklin_l2",
    toPlatformId: "plt_franklin_l6",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_santa_ana_l2_l5",
    fromPlatformId: "plt_santa_ana_l2",
    toPlatformId: "plt_santa_ana_l5",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_puente_l2_l3",
    fromPlatformId: "plt_puente_cal_y_canto_l2",
    toPlatformId: "plt_puente_cal_y_canto_l3",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: true,
  },
  {
    id: "itf_plaza_de_armas_l3_l5",
    fromPlatformId: "plt_plaza_de_armas_l3",
    toPlatformId: "plt_plaza_de_armas_l5",
    walkingSeconds: 180,
    accessibilityFriendly: true,
    platformChange: true,
  },
  {
    id: "itf_irarrazaval_l3_l5",
    fromPlatformId: "plt_irarrazaval_l3",
    toPlatformId: "plt_irarrazaval_l5",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_nunoa_l3_l6",
    fromPlatformId: "plt_nunoa_l3",
    toPlatformId: "plt_nunoa_l6",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_plaza_egana_l3_l4",
    fromPlatformId: "plt_plaza_egana_l3",
    toPlatformId: "plt_plaza_egana_l4",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: true,
  },
  {
    id: "itf_vicuna_mackenna_l4_l4a",
    fromPlatformId: "plt_vicuna_mackenna_l4",
    toPlatformId: "plt_vicuna_mackenna_l4a",
    walkingSeconds: 60,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_vicente_valdes_l4_l5",
    fromPlatformId: "plt_vicente_valdes_l4",
    toPlatformId: "plt_vicente_valdes_l5",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
  {
    id: "itf_nuble_l5_l6",
    fromPlatformId: "plt_nuble_l5",
    toPlatformId: "plt_nuble_l6",
    walkingSeconds: 120,
    accessibilityFriendly: true,
    platformChange: false,
  },
];
